### ISSUE TITLE
On Home Page, text when you swipe an article is too long

### ISSUE THREAD

**Issue by roukydesbois** [wallabag/ios-app#100]
See this screenshot:

![2017-06-27 20-18-12 1870](https://user-images.githubusercontent.com/11874580/27603423-56390d08-5b76-11e7-9c93-19219556933a.png)

I think you could put the icons, as you did for the article view.

**Comment by bourvill** [comment]
And fix the missspelling 😣

**Comment by roukydesbois** [comment]
Well, if you have an icon you won't have a misspell anymore \o/

**Comment by bourvill** [comment]
I am embarrassed to put a picture. The applications that provide it go through tricks. With ios11 it will be possible to put natively, I think I will wait to put the logos natively without tricks

I added a return to put on two lines and fix the misspelling

this change will be available in next release 2.1.2
