### ISSUE TITLE
App hangs/freeze

### ISSUE THREAD

**Issue by 70B43r** [wallabag/ios-app#102]
Since version 2 the app hangs and freezes on article view.
Espeachially on scrolling through an article, the app stops working and does not respond to any input.

This happens on short texts and also on long ones.

Version: 2.1.1 build 58 @ iPhone 7 with iOS 10.2.3 (14F89)

**Comment by bourvill** [comment]
Hello, can you provide an article example ?

**Comment by 70B43r** [comment]
It's nearly every article.

Samples from the video are
https://opensource.guide
http://www.firsttimersonly.com (programming; no p0rn)

[opensource.zip](https://github.com/wallabag/ios-app/files/1111106/opensource.zip)
[firsttimersonly.zip](https://github.com/wallabag/ios-app/files/1111107/firsttimersonly.zip)

**Comment by bourvill** [comment]
Thank you for your feedback and video!

We investigate

**Comment by bourvill** [comment]
this change will be available in next release 2.1.2
