### ISSUE TITLE
Cannot configure the iOS version

### ISSUE THREAD

**Issue by Gui13** [wallabag/ios-app#104]
I have an hosted version of wallabag, and the iOS app (the one on the App Store) asks for :
- the server address (I'm ok with this)
- then a clientId and a client secret (oauth creds?), which I don't understand
- then a user and pass, I which even when filled with the correct value will lead to an error message

Is it normal to ask for Oauth2 credentials? I mean, I'm hosting the app, not using the hosted environment.

Or maybe the App Store version is outdated?

**Comment by bourvill** [comment]
Hello Gui13

your clientId and clientSecret can be found in your Developer Page on your wallabag instance. You need to create one.

tell me if you are OK after this

**Comment by Gui13** [comment]
Bourvill, I have understood the problem.

I couldn't figure out why you need an Oauth2 for connection, but I created the app in my instance anyway, and continued the process.

The real issue was that my LetsEncrypt certificate had expired. After renewing it, the app worked correctly.

I think that #98 is related to the same problem. Maybe you could add a popup prompting for user consent when a certificate is invalid?

**Comment by palouf34** [comment]
Hi,

I make this token on my computer but why write it on this iPhone app's???

This proves is very difficult for obtain my article....

regards.
