### ISSUE TITLE
Top bar disappearing on the homepage

### ISSUE THREAD

**Issue by roukydesbois** [wallabag/ios-app#105]
To reproduce:
- open an article in article view
- scroll quickly down so that the top bar disappears
- archive or delete it using the icons at the bottom
At this stage, the app goes back to the home page, and the top bar is hidden. Even scrolling quickly up or down doesn't make the top bar appear again. 
A screenshot (with the articles I'm reading as a bonus ^^):

![2017-06-28 06-05-58 1871](https://user-images.githubusercontent.com/11874580/27881452-f27456f2-61c8-11e7-951d-2a3abce04815.png)

**Comment by bourvill** [comment]
this change will be available in next release 2.1.2
