### ISSUE TITLE
App freezes with 2.000+ unread articles

### ISSUE THREAD

**Issue by gnppn** [wallabag/ios-app#109]
As discussed on Twitter: https://twitter.com/Gnppn/status/885880192392200192

I have more than 2.000 unread articles in my library (on wallabag.it) and the iOS app freezes almost a minute on launch (after a blank screen) and remains really laggy once the content loaded, making opening articles quite difficult.

Thanks!

Devices: iPhone 6s and iPad mini 4 on iOS 10.3.2
App version: 2.1.2
Wallabag server: 2.2.3

### Steps to reproduce/test case

Open the wallabag iOS app, connected to an account with more than 2.000 entries, and new ones to load, with the "Unread articles" on default view.

### Improvement
Do you have a solution for this? Wouldn't limiting the number of shown articles by default help?

**Comment by dgoujard** [comment]
I have the same issue. When I try to add new entries with the share action it freeze too.

**Comment by bourvill** [comment]
How many articles do you have ?

**Comment by dgoujard** [comment]
241 articles (tested on iPhone 6 and iPad Pro 10.5).

**Comment by bourvill** [comment]
I've identified the problem and I'm working on it.

Thanks for your feedback

**Comment by bourvill** [comment]
Hello @dgoujard,
Are you interested in testing the beta build that will potentially fix your bug?
@gnppn is already in beta, and it work for him

Send me your email address at maxime.m62@gmail.com

**Comment by dgoujard** [comment]
It's ok with the TestFlight release 👍

**Comment by bourvill** [comment]
this fix will be available in next release 2.2
thanks for your feedback !
