### ISSUE TITLE
After migration from Instapaper, app shows all articles as read

### ISSUE THREAD

**Issue by hasanen** [wallabag/ios-app#115]
| Q             | A
| ------------- | ---
| Device?       | iPad Pro
| Device Os version    | 10.3.3
| App Version   | 2.1.2 build 61
| Wallabag server version | Not sure, using wallabag.it

### Steps to reproduce/test case

I imported my all articles ~3500 from instapaper yesterday to wallabag.it. I have around ~300 unread articles. I just downloaded iOS-app and it shows only 2 unread articles, the ones I've added into service after import.

### Improvement
App would show same articles as unread than is shown in web (wallabag.it).

**Comment by bourvill** [comment]
Thank you for choosing wallabag.it!
I'm sorry for the bug, I think it's linked to a sync issue with a lot of items like # 109.
I am currently working on a fix with version 2.2 that will come out quickly.

I keep you informed. thank you for your feedback

**Comment by bourvill** [comment]
Hello @hasanen ,
Are you interested in testing the beta build that will potentially fix your bug?

Send me your email address at maxime.m62@gmail.com

**Comment by hasanen** [comment]
Sent an email to you.

**Comment by bourvill** [comment]
Thank. Sended on your appleID email

**Comment by hasanen** [comment]
I tested the version and it fixed this bug!

However, not sure if logging out and in was necessary, but I did it anyway.

**Comment by bourvill** [comment]
Cool, thanks you for your feedback! 

You can use this build until the release come to the appStore.

I think will be released in few week. 

we need to fix some other bugs and add new features.

I will close this issue. thanks
