### ISSUE TITLE
Widget freezing !

### ISSUE THREAD

**Issue by mayaahh** [wallabag/ios-app#116]
| Q             | A
| ------------- | ---
| Device?       | iPhone/iPad
| Device Os version    | 9.0/10.0
| App Version   | 2.0
| Wallabag server version | 2.0

### Steps to reproduce/test case

When trying to add a web page to wallabag, from Chrome for example, an icon show up and never go away. Nothing can be done and I have to quit and relaunch the app !
I have made screenshots but I don't know how to upload them.

**Comment by mayaahh** [comment]
The screenshot:
![img_4084](https://user-images.githubusercontent.com/30800676/29033046-0365cd58-7b94-11e7-8e39-57316ac603b3.PNG)

**Comment by bourvill** [comment]
Thanks for your bug report.

Can you give me the url of the article you are trying to add?

**Comment by mayaahh** [comment]
My example were from inside a dedicated app. One example url can be : http://www.lemonde.fr/planete/article/2017/08/07/en-2100-40-de-l-humanite-sera-africaine_5169434_3244.html 
BUT I thinks that's not the problem because I have the same difficulty if I use Safari to add any web page. It could be the app not compatible with my phone (iphone 5s, last version of IOS) or a problem with my server ?

**Comment by mayaahh** [comment]
![img_4086](https://user-images.githubusercontent.com/30800676/29033605-dcbc0b16-7b95-11e7-8624-763e707b7df4.PNG)

**Comment by bourvill** [comment]
Is your application fully configured?

Have you tried to add article inside app ?

**Comment by mayaahh** [comment]
Hi
I think my configuration is ok. I can add a link from inside the application, it works and I can see it on other devices. 
Thanks

**Comment by brabalan** [comment]
I have the same issue. Adding anything through the extension widget (from Safari or Tweetbot) leaves the application stuck, displaying the wallabag icon as above.

**Comment by bourvill** [comment]
@mayaahh @brabalan can you confirm your version number of wallabag app?

you can find them in "about" menu

**Comment by brabalan** [comment]
I solved the issue. I use 2.1.2 build 61, and as I went to look it up, I noticed there were no articles in the app. So I logged out and entered back my credentials, and now the articles are there and saving articles using the widget works.

**Comment by bourvill** [comment]
Yes, I think the problem is because of an authentication problem in the main application.

I will add controls to avoid blocking the phone
