### ISSUE TITLE
Possible to appear as Apple News share destination?

### ISSUE THREAD

**Issue by greigdp** [wallabag/ios-app#118]
| Q             | A
| ------------- | ---
| Device?       | iPad
| Device Os version    | 10.3.3
| App Version   | 2.1.2
| Wallabag server version | 2.0

### Improvement
The default Apple News app has a share facility. This lets you send to Mail, Reminders, Notes, etc. It seems that third party apps can be listed here (Firefox can appear here). It would be nice if Wallabag was able to appear here as a share destination from Apple News (like it does for sharing a website from Safari or similar). 

It appears that the share returns a URL to content on https://apple.news (which acts as a redirect to the original article URL when accessed from a PC browser), so it would appear possible for Wallabag to handle and let you store these links.

**Comment by thibaultamartin** [comment]
The Wallabag app is being rewritten. Current major won't get a fix for this, and it's not yet planned for the 5.0.x versions. We're focusing on polishing the existing features before diving into new ones.

If you want to join the beta, you can [follow the Testflight link](https://testflight.apple.com/join/RF9hzKHt). Keep in mind the beta still is unstable, and any update can completely break the app (and potentially do some nasty things on your Wallabag instance).

Apple News has not been release in France, and most people working in this app are French, so it's kinda hard for us to test :)

That said, the Wallabag extension (_i.e._ the _share to_ button) has been worked on in the beta for the v5. Can you do some testing and confirm it does work for you?

**Comment by greigdp** [comment]
I've tried to join the Testflight, but am told it's no longer accepting participants. Happy to join the beta however if it helps.

**Comment by bourvill** [comment]
Hello
You can use this link 
https://apple.co/2HRfIcY

i will update the link in readme

**Comment by greigdp** [comment]
Thanks - can confirm that on the beta, there's a "share to wallabag" from the Apple News app. Also, the "correct" URL to the article itself, rather than the https://apple.news redirect, is added to Wallabag.

Closing this, since it all seems to be working. Thanks
