### ISSUE TITLE
The requested URL was not found on the server

### ISSUE THREAD

**Issue by laurentperrinet** [wallabag/ios-app#119]
| Q             | A
| ------------- | ---
| Device?       | iPhone and iPad
| Device Os version    |  10.0
| App Version   | 2.0
| Wallabag server version | 2.0

### Steps to reproduce/test case

I am using FramaBag and could sync correctly on v1. I now have problems syncing with v2.
On the configuration page, I entered

URL : https://framabag.org
User ID : laurentperrinet
Token ID: <the one I get on the configuration page of the RSS>

However, I get a "the requested URL was not found onb the server"... I am doing something wrong?

**Comment by bourvill** [comment]
Hello, can you post screenshot with the error ?

**Comment by laurentperrinet** [comment]
Here is the screenshot of the error message:
![img_0798](https://user-images.githubusercontent.com/381808/29636619-fb56da30-8859-11e7-86b4-dde3ce8b2864.PNG)

**Comment by bourvill** [comment]
Ok, you do not use the official version of Wallabag.

I can not provide support for this application.


You can found the official app (of this repos) wallabag ios https://www.google.fr/url?sa=t&rct=j&q=&esrc=s&source=web&cd=2&ved=0ahUKEwit1bjGmO7VAhULVxQKHXDjAXYQFggzMAE&url=https%3A%2F%2Fitunes.apple.com%2Ffr%2Fapp%2Fwallabag-2-official%2Fid1170800946%3Fmt%3D8&usg=AFQjCNEi1mPfkZ28nl4FllXwEOz_y1yHdQ

**Comment by laurentperrinet** [comment]
Thanks a lot for the prompt answer! It now works perfectly. I have commented both apps (the official and the one I was using) on the apple store.

Note: when I was entering the url as https://framabag.org/ I had the error as shown in the screenshot, though I had no problem when using https://framabag.org 

![img_0799](https://user-images.githubusercontent.com/381808/29657980-02d3c616-88c2-11e7-8e7c-2788b8c645af.PNG)

**Comment by j0k3r** [comment]
poke @tcitworld :point_up:
