### ISSUE TITLE
The app does not download new articles

### ISSUE THREAD

**Issue by papernoise** [wallabag/ios-app#120]
| Q             | A
| --             | --
| which flavour of Wallabag? | Framabag.org
| Device?       | iPad Mini 2
| Device Os version    | 10.1.1
| App Version   | 2.1.2
| Wallabag server version | 2.0

### Steps to reproduce/test case

1. Add some articles to Wallabag's web app (not the iOS app)
2. try to refresh the app on iOS, either by waiting for it to refresh, or by dragging the article list down until the spinning wheel does appear
3. notice that nothing changes and the articles you have added are not showing up in the list

some further info that might be useful: deleting or archiving an article on the iOS app also won't propagate the change to the webapp, so it seems that there might be a general communication problem between the app and Framabag.
Disconnecting the account and adding it back will download the current article list. But after that the issue will still be there.

**Comment by bourvill** [comment]
Hello,
Thanks for this info.
How many articles do you have in your wallabag?

Because if you have a lot of article a bug of the same kind has been identified. It will be resolved in version 2.2 of the application

**Comment by papernoise** [comment]
Sure thing, you're welcome! I do not have a lot of articles, 62 in total (including archived ones).
I did some more testing and the problem might be linked to running the app offline. If I disconnect, reconnect then everything works fine and I can also terminate the app, launch it again, and it will keep syncing everything with the server. I think the problem starts when I launch the app without an internet connection (happens a lot... and actually, that's one of the main benefits of using Wallabag for me). From there on, I can terminate and relaunch the app even with internet connection and it will not sync anymore.

**Comment by bourvill** [comment]
Okay, thank you for your comments.

Indeed, the application below 2.2 has priority over online mode.
With the version 2.2 which arrives soon the offline mode will take priority.

**Comment by papernoise** [comment]
cool, thanks a lot! Will wait for 2.2 then!

**Comment by jb911** [comment]
Hello,

I have the same problem with Wallabag 2.2.3 and the latest IOS app with my iPad.
The new articles are not downloaded.

**Comment by papernoise** [comment]
I have updated to the latest version and still have the same issue here. Nothing seems changed the problem is still present and the steps to reproduce it are the same.

**Comment by wiflye81** [comment]
Same issue on my self hosted server, latest version, here is the log from web server:

127.0.0.1 - - [25/Oct/2017:09:18:33 +0000] "GET /api/entries?page=1 HTTP/1.1" 401 106 "-" "wallabag/69 CFNetwork/887 Darwin/17.0.0"
127.0.0.1 - - [25/Oct/2017:09:18:34 +0000] "POST /oauth/v2/token HTTP/1.1" 400 91 "-" "wallabag/2.3 (fr.district-web.wallabag; build:69; iOS 11.0.3) Alamofire/4.5.1"

Hope it helps.

**Comment by bourvill** [comment]
thank you for your feedback. I think it's an authentication problem. I will try to solve the problem. to enjoy the application try to disconnect and reconnect

**Comment by wiflye81** [comment]
Thanks for your reply, I confirm it works with this workaround.

**Comment by papernoise** [comment]
> thank you for your feedback. I think it's an authentication problem. I will try to solve the problem. to enjoy the application try to disconnect and reconnect

This works only temporarily for me (on Framabag). Disconnecting and reconnecting will sync properly with the server, but the next time I use the application offline the problem will return.

**Comment by eli-oat** [comment]
I'm seeing the same behavior reported by @papernoise 

I'm able to get the app to refresh new items if I sign out and sign back into the app, but the app doesn't refresh on its own. Interestingly, not finding any error logs server-side. Haven't checked my device logs, yet. 

- Running iOS 11.0.3 on an iPhone 8 Plus
- App version 2.3, build 69
- Self hosted instance of Wallabag, release-2.2.3

**Comment by bourvill** [comment]
@eli-oat can you copy the few lines of log like @wiflye81 at the moment the application tries to access your instance?

**Comment by eli-oat** [comment]
Sorry for the delay — are you hoping for logs form my server or my iOS device, or both? 

My server logs aren't showing any errors (I may need to configure logging in Wallabag config, though). 

I haven't had a chance to pull any logs off of my iOS device, but will try to do that soon. 

I'm wondering if this could be an https:// issue? I use a re-direct from http:// to https://, so all traffic to my server is forced over SSL, no matter what. Could this be impacting anything?

**Comment by pmciano** [comment]
I'm seeing this issue on iOS `11.1.1` using the Wallabag `2.3` iOS client with the wallabag.it service.

> Disconnecting the account and adding it back will download the current article list. But after that the issue will still be there.

For me, disconnecting and reconnecting inside of the iOS app is not necessary to temporarily address the issue. If I just quit the iOS app from the multitask view and relaunch it, the latest articles are pulled down.

**Comment by das-schaf** [comment]
Relaunching the app doesn't fix the issue for me. Currently using Wallabag 2.3 with iOS  11.2. No errors in the logs.

**Comment by nicosomb** [comment]
I heard that an alpha release will come in coming days from @bourvill ;-)

**Comment by bourvill** [comment]
Yes a new version is in preparation. It only focuses on connection problems. All the work with the API is rewritten, thanks for your patience

**Comment by bourvill** [comment]
this fix will be available in 2.3.1 release
