### ISSUE TITLE
Wallabag overlay freezing on top of other apps

### ISSUE THREAD

**Issue by gnppn** [wallabag/ios-app#125]
| Q             | A
| ------------- | ---
| Device?       | iPhone 6s / iPad mini 4
| Device Os version    | iOS 11.1.2
| App Version   | 2.3
| Wallabag server version | 2.3

### Steps to reproduce/test case

From the Share menu in third party apps (Narwhal, Reeder, Twitter), save a link to the wallabag app. The overlay appears, but instead of disappearing, it freezes. The article isn't added to my wallabag account.

The only way I found to get back to the app is closing it from the multitask menu after a minute of freezing, and relaunching it. I can't seem to reliably reproduce it. The problem can manifest when the app is already open or closed.

Please note that I have a 11.000+ articles base, which doesn't seem to help the iOS app.

![img_2032](https://user-images.githubusercontent.com/22668283/33126549-3368fa1c-cf85-11e7-8020-421897bfde5d.PNG)

### Improvement

Save the article when prompted from a third party app or, after a certain time, close the overlay and display an error.

Thanks!

**Comment by gnppn** [comment]
The problem has been fixed (for now) by reinstalling the app.

**Comment by grizzee** [comment]
Same problem here (iPhone SE, iOS 10.3.3). But reinstalling doesn't help.

**Comment by bourvill** [comment]
this fix will be available in 2.3.1 release
