### ISSUE TITLE
App crashing on launch

### ISSUE THREAD

**Issue by gnppn** [wallabag/ios-app#126]
| Q             | A
| ------------- | ---
| Device?       | iPhone 6s
| Device Os version    | 11.1.2
| App Version   | 2.3
| Wallabag server version | 2.3

### Steps to reproduce/test case

When opening the wallabag app, it displays a blank screen for several seconds. It can then display my last saved articles or crash. Relaunching after a crash gives a blank screen then the article list, in my latest test.

I don't have reliable steps to reproduce it, it seems random to me.

I have 11.000+ articles, the problem seems to mimick the #109 one.

### Improvement
Display the article list faster and... not crash. :)

Thanks!

**Comment by bourvill** [comment]
this error are occured after upgrading your server version ?

**Comment by gnppn** [comment]
I already had crashes with the previous server version.

**Comment by gnppn** [comment]
I get a new crash, while scrolling a long article when the app is syncingafter reinstalling it.  After some scrolling, the screen turns to black for two/three seconds then the app crashes. I get it on my iPhone 6s and iPad mini 4.

**Comment by bourvill** [comment]
Can you activate the crash report to the developer?

https://support.apple.com/en-us/HT202100

**Comment by gnppn** [comment]
Done on both devices. The app crashed again while scrolling in my test article: https://www.mediapart.fr/journal/france/180416/tariq-ramadan-enquete-sur-un-epouvantail-15?onglet=full

**Comment by bourvill** [comment]
I think this issue is solved. But we will open a new issue for the app running more smoothly
