### ISSUE TITLE
First configuration improvements

### ISSUE THREAD

**Issue by gnppn** [wallabag/ios-app#128]
| Q             | A
| ------------- | ---
| Device?       | iPhone 6s/iPad mini 4
| Device Os version    | 11.1.2
| App Version   | 2.3
| Wallabag server version | 2.3

### Steps to reproduce/test case

Configure the app for the first time.

### Improvement

On the first page, after tapping "Register", the user should get a list of known servers (wallabag.it, wallabag.org, framabag.org...).

When configuring a custom server, the page should suggest the "http://" or "https://" prefix, via a separate prefilled field if possible/

The next page "clientID/clientSecret" has English text in the French version. The "Open my developer page" should be distinguished as a link.
This also goes for the "Register" link on the first page.

Another suggestion would be to ditch the "Register" first page altogether, since there's no actual choice for the user. A registration page with a big logo, a short list of servers, a link to add a custom one and a button would be better imho.

Thanks for reading this. :)

**Comment by bourvill** [comment]
Great!
But I think that the list of services will not be possible. Apple has already declined the application if we were talking about wallabag.it (because of the subscription to the service that does not go through their subscription)

**Comment by gnppn** [comment]
Thanks for the answer. That's disappointing but expected from Apple I guess. :(

**Comment by bourvill** [comment]
this change will be available in next release. I can only add the missing translate.

Thanks
