### ISSUE TITLE
Disconnect does not redirect to login screen every time

### ISSUE THREAD

**Issue by JanJastrow** [wallabag/ios-app#129]
| Q             | A
| ------------- | ---
| Device?       | iPhone/iPad
| Device Os version    | 11.2
| App Version   | 2.3 (69)
| Wallabag server version | 2.2.3

### Steps to reproduce/test case

- Open App (logged into your account)
- Menu -> Disconnect

### Improvement
In my testing/usage of the app I had to reset my login credentials a few times.
In most of my tests, after clicking "Disconnect", I do not get to the Setup screen but instead to an empty "Articles overview"

**Comment by bourvill** [comment]
this fix will be available in 2.3.1 release
