### ISSUE TITLE
Display a badge of how many unread article on the icon

### ISSUE THREAD

**Issue by j0k3r** [wallabag/ios-app#13]
Display a badge on the icon app with the number of unread articles.
User should be able to disable this feature in the app.

**Comment by devianer** [comment]
Hi where exactly would you see the number of unread articles? I'm trying to help out here a bit but still finding my way around the app.

**Comment by j0k3r** [comment]
On the app icon on the springboard.

**Comment by bourvill** [comment]
this change will be available in next release
