### ISSUE TITLE
Disconnect should have a warning/confirmation dialogue

### ISSUE THREAD

**Issue by JanJastrow** [wallabag/ios-app#130]
| Q             | A
| ------------- | ---
| Device?       | iPhone/iPad
| Device Os version    | 11.2
| App Version   | 2.3 (69)
| Wallabag server version | 2.2.3

### Steps to reproduce/test case

- Open App (logged into your account)
- Menu -> Disconnect

### Improvement
Disconnect-function should have a warning/confirmation dialogue.
It's to easy to accidentally click on the item and then have to go through setup again.

**Comment by bourvill** [comment]
this change will be available in next release.
Thanks
