### ISSUE TITLE
Unexpected Error while setup/login

### ISSUE THREAD

**Issue by JanJastrow** [wallabag/ios-app#131]
| Q             | A
| ------------- | ---
| Device?       | iPhone/iPad
| Device Os version    | 11.2
| App Version   | 2.3 (69)
| Wallabag server version | 2.2.3

### Steps to reproduce/test case

- Fresh installation
- Entering your server URL

### Improvement
While trying to login I had the issue that I could not login into my instance, even with correct credentials. (Copy'n'pasted from 1Password)
While testing I found that I can login successfully, if I remove the trailing slash from my server URL.

https://wallabag.myserver.eu/ => Does not work
https://wallabag.myserver.eu => Does work

I don't know if that's a mistake in my nginx setup, but I think the app should be able to test a login-url with removed trailing-slash on its own.

**Comment by bourvill** [comment]
This problem was fixed. Thx
