### ISSUE TITLE
Can't sync articles

### ISSUE THREAD

**Issue by jeronimofagundes** [wallabag/ios-app#134]
| Q             | A
| ------------- | ---
| Device?       | iPhone SE
| Device Os version    | 11.2.1
| App Version   | 2.3.1 build 72
| Wallabag server version | 2.3.1

### Steps to reproduce/test case

1. Setup a wallabag self hosted install through https
2. Save a good amount of articles in it (I have 442)
3. Download app for iphone
4. Register inside the app with a brand new client id + secret
5. The register succeeds, but no articles are shown. 
6. Try saving a new article. It is not saved (does not show up in app list, not in the web browser access).

**Comment by bourvill** [comment]
Hello, 

Do you have any log on your server? (web access/error log for example)

**Comment by jeronimofagundes** [comment]
I looked at the logs, but it does not seem to reach the server at all. The registration succeeds, however (sometimes it shows "authentification error" if I delete the app and install it again).

**Comment by bourvill** [comment]
I think you have a problem with the registered url. When your are on article list, click on menu and disconnect. Double check your url server. And tell me it's ok

**Comment by jeronimofagundes** [comment]
This is before disconnecting.
![img_0183](https://user-images.githubusercontent.com/351016/34387842-9959658e-eb17-11e7-9f9e-ba6921498138.PNG)

URL screen, typing the correct URL:
![img_0184](https://user-images.githubusercontent.com/351016/34387851-aacc61e0-eb17-11e7-9e4c-c93c508436e9.PNG)

Client ID+Secret Screen
![img_0185](https://user-images.githubusercontent.com/351016/34387861-b5e61152-eb17-11e7-9a2f-cb9e815019b5.PNG)

Didn't attached the following screen, asking for username and password, but it showed up.

After logging in and selecting "All articles":
![img_0186](https://user-images.githubusercontent.com/351016/34387886-cc6edc7e-eb17-11e7-93d9-419d5ed129f7.PNG)

**Comment by bourvill** [comment]
Strange, you dont have error alert in article list ?

**Comment by jeronimofagundes** [comment]
My bad. :-(
It seems was something wrong in my wallabag install. I installed it using the docs for dedicated hosting, but in a shared hosting (I didn't see at first was a package for shared hostings).
Reinstalling wallabag on my server with the correct package solved the problem.
