### ISSUE TITLE
Probably something wrong with the local storage

### ISSUE THREAD

**Issue by LordEidi** [wallabag/ios-app#136]
| Q             | A
| ------------- | ---
| Device?       | iPhone/iPad (both)
| Device Os version    | 11.2.1
| App Version   | 2.3.1
| Wallabag server version | not relevant

It looks as if the app does not update the access_token it gets from the server. After getting a new access token via POST /oauth/v2/token the app uses the old access_token for the next request (ignoring the new one). Since the server responds with an access denied to that, the app again tries to authenticate, getting a new access token, ignoring it again. Never ending loop ensues.

### Steps to reproduce/test case

- If you have a wallabag 2 app registered on a server of your choice, invalidate the access_token, server side.
- Reopen the wallabag app. The app immediately tries to get new articles. Since the old access_token is invalid (server returns a 401), the app gets a new access_token via oauth2 API and tries to refresh the article list with the old access_token, completely ignoring the new one.
- Disconnect from the server (from within the app)
- The app continues trying to update the article list, getting a 401, getting a new access_token, trying to update the article list, getting a 401, etc. Although you just disconnected the app.
- Leave and kill the wallabag app
- Deinstall the wallabag app
- Reinstall the wallabag app
- Start the app, you get greeted with the registration screens.
- Enter your credentials
- The app starts a POST request to /oauth/v2/token and gets a new access_token
- The app reuses the old access_token, trying to get the list of articles.

### Improvement

- Accepting the new access token when getting one from the server.
- Implementing some sort of timeout where the app stops the cycle between authenticating and running into a 401 access denied.

**Comment by bourvill** [comment]
Release is out, Hope you enjoy it, and fixed your issue.
Thank for your patience.
