### ISSUE TITLE
Wallabag fetch articles twice

### ISSUE THREAD

**Issue by ghost** [wallabag/ios-app#138]
| Device?       | iPhone
| Device Os version    | 11.2.2
| App Version   | 2.3.1 build 72
| Wallabag server version | 2.3.1

### Steps to reproduce/test case

If i save articles at wallabag (web version) und refresh the ios App i see all articles twice.

**Comment by mostlyjason** [comment]
I've seen this on a subset of my articles. Each was an article I added with the app and was created when I ran into #139. They were missing on the devices I added articles from, and my second iOS device they were doubled. Thinking I accidentally added them twice, I deleted the extra ones. However, when I refreshed the original articles were deleted as well.

**Comment by bourvill** [comment]
this fix will be available in next release
