### ISSUE TITLE
Wallabag can‘t save safari sites 

### ISSUE THREAD

**Issue by ghost** [wallabag/ios-app#139]
Device? | iPhone
| Device Os version | 11.2.2
| App Version | 2.3.1 build 72
| Wallabag server version | 2.3.1

Wallabag app cant save articles from safari. I got always the error „please open the app and add it manual“. But manual doesnt work either. 

Testsite to add: http://www.sueddeutsche.de/politik/spd-grosses-misstrauen-gegenueber-frau-merkel-1.3827744

**Comment by mostlyjason** [comment]
+1

**Comment by aleohl** [comment]
+1

Same error for me.

**Comment by bourvill** [comment]
After many test on my device, i have not problem with this url. I think the main cause is your wallabag app are unsynced. Can you try logout and re link your account ? Sorry for this

**Comment by mostlyjason** [comment]
I noticed the app becomes unregistered by itself after some time, like perhaps every other week. It remembers the url and tokens, but not my password and i have to put it in again. I always keep the same tokens but I have to add my password again.

Just today I added my password again, it synced articles, then I tried to add an article from medium, and it gave the error again. I went to the wallabad app, refreshed the articles and it didn't show up. I went to my web browser and I saw the article in the list. Perhaps this is related to #138 ?

**Comment by bourvill** [comment]
You run your own instance of wallabag server?

**Comment by mostlyjason** [comment]
Yes


On Sun, Feb 4, 2018, at 1:06 PM, Maxime wrote:
> You run your own instance of wallabag server?


> — You are receiving this because you commented. Reply to this email
> directly, view it on GitHub[1], or mute the thread[2].> 

Thanks,
Jason


Links:

  1. https://github.com/wallabag/ios-app/issues/139#issuecomment-362939669

**Comment by gerhard-tinned** [comment]
+1

I have a hosted wallabag (Docker container) and I cannot sync. The iOS app accepts the tokens and the user/password but shows an empty list.

**Comment by paoll** [comment]
I have the same issue here. I'm using the last docker version and my ios app is uptodate.

**Comment by gerhard-tinned** [comment]
I was digging into the issue. I created a network trace of the sync attempt. It seems that the app sends a request to the wallabag instance (running as well in a docker image). The wallabag instanc is responding to the apps request with a list of articles as I could see in the network trace. 

This leads me to the conclusion that the iOS app for some reason dies not handle the response from the wallabag server as it is supposed to. But to debug the reasin for that I would need someone able todebug the iOS app.

**Comment by bourvill** [comment]
Release is out, Hope you enjoy it, and fixed your issue.
Thank for your patience.

**Comment by lilarcor** [comment]
Thank you, the issue has been resolved with the latest release
