### ISSUE TITLE
Session timeout, logged out 

### ISSUE THREAD

**Issue by joncutrer** [wallabag/ios-app#140]
| Q         | A
| ------------- | ---
| Device?       | iPhone X
| Device Os version    | 11.x
| App Version   | 2.0
| Wallabag server version | 2.0 (paid hosted)

### Steps to reproduce/test case

my login session to the iOS app doesn’t lasts more that a day.  I’m constantly having to reauthenticate.

**Comment by bourvill** [comment]
hi, thanks for your feedback.

What your provider for your wallagag instance ?

**Comment by joncutrer** [comment]
https://app.wallabag.it

**Comment by lsf3og** [comment]
Same problem for me on IPad and IPhone with wallabag.it and IOS 11.x

**Comment by notFloran** [comment]
Same problem on iPhone and iPad with iOS 11 for `app.wallabag.it`.

When I launch the app I have the message "authentication error".

**Comment by bourvill** [comment]
I work on it, stay tuned

**Comment by oakbrad** [comment]
Same for me, never lasts more than a day. I self host and other Wallabag clients haven't had issues.

**Comment by bourvill** [comment]
Sorry for the delay and the wait concerning the resolution of the problems.

You can found some explanation https://github.com/wallabag/ios-app/issues/142#issuecomment-379434985

A beta is rolled out internally. Stay tuned

**Comment by bourvill** [comment]
Release is out, Hope you enjoy it, and fixed your issue.
Thank for your patience.

**Comment by lsf3og** [comment]
BTW.
I mailed you some weeks ago regarding a double payment for an annual subscription. You never reacted to it. Could you please look into it?

Am 2. Mai 2018, 12:46 +0200 schrieb Maxime Marinel <notifications@github.com>:

**Comment by bourvill** [comment]
Hi @lsf3og i dont have subscription directly in Wallabag 2 official? 

what are you talking about?

Which service do you use?

**Comment by lsf3og** [comment]
Wallabag.it

Am 2. Mai 2018, 16:12 +0200 schrieb Maxime Marinel <notifications@github.com>:

**Comment by lsf3og** [comment]
Thanks

Am 2. Mai 2018, 16:20 +0200 schrieb Maxime Marinel <notifications@github.com>:
