### ISSUE TITLE
auto logged out

### ISSUE THREAD

**Issue by lilarcor** [wallabag/ios-app#144]
| Q             | A
| ------------- | ---
| Device?       | iPhone
| Device Os version    | 11.3
| App Version   | 2.3
| Wallabag server version | 2.3.2

I got my id logged out from time to time, and I have to re-key in my password to log in. Don't know how it happened.

**Comment by bourvill** [comment]
what service do you use?

**Comment by lilarcor** [comment]
i don't know about the service you mentioned, can it be more specific ?

**Comment by bourvill** [comment]
Where is your wallabag instance? On your on server? Or service like wallabag.it ?

**Comment by lilarcor** [comment]
oh, it's on my personal server. I don't have a static ip for my internet connection. So my server's ip could be updated, and I access it through DDNS, I am not sure if that will cause the issue

**Comment by lsf3og** [comment]
I have the same problem with wallabag.it.

**Comment by pheraph** [comment]
Same here with a self hosted wallabag (static IP). :-(

**Comment by bourvill** [comment]
Do you have a message when you are logged out? Or app crash?

**Comment by lilarcor** [comment]
no app crash. App remembers server URL,client_ID , client_secret and username, I have to keep pressing next then input password to re-log on.

**Comment by timscha** [comment]
I habe the same problem on my iPad with the latest iOS 11.3 and self hosted wallabag.
It looks like the App forget my session. All details like Client id are Safed, but I had to reconfirm everything in the setup at the beginning. There was no crash or something else.

**Comment by bourvill** [comment]
I think the problem has been solved with the latest version (2.3.3).

If the problem persists open a new issue. Thank
