### ISSUE TITLE
Custom margin width

### ISSUE THREAD

**Issue by kour1er** [wallabag/ios-app#146]
Would it be possible to add customisable margin width? I like to have some space at the edges for more comfortable reading. Thank you

**Comment by thibaultamartin** [comment]
The Wallabag app is being rewritten. Current major won't get a fix for this, and it's not yet planned for the 5.0.x versions. We're focusing on polishing the existing features before diving into new ones.

If you want to join the beta, you can [follow the Testflight link](https://testflight.apple.com/join/RF9hzKHt). Keep in mind the beta still is unstable, and any update can completely break the app (and potentially do some nasty things on your Wallabag instance).

I leave this issue open to keep track of it, but it may never actually implemented if nobody from the development side has interest in. Everyone is a volunteer here :)

**Comment by kour1er** [comment]
Heh fair enough - thanks for all your work.

ps that Testflight link says not accepting any new testers right now - just in case you were unaware.

**Comment by thibaultamartin** [comment]
Yes someone told us that. That's odd. I'll keep you posted when this is sorted out :)

**Comment by bourvill** [comment]
Hello you can use this link : https://apple.co/2HRfIcY

**Comment by kour1er** [comment]
@bourvill the new link works great - cheers

**Comment by bourvill** [comment]
This functionality will not be integrated.
