### ISSUE TITLE
Password needs to be reentered after a few days of usage

### ISSUE THREAD

**Issue by lsf3og** [wallabag/ios-app#149]
| Q             | A
| ------------- | ---
| Device?       | iPhone/iPad
| Device Os version    | iOS 12 beta
| App Version   | 2.3.3
| Wallabag server version | whatever wallabag.it uses

### Steps to reproduce/test

After some days of usage I have to renter my password. 

### Improvement
If your issue involves a suggestion for improvement or a request to add functionality. You can delete this template and describe your request

**Comment by JanJastrow** [comment]
Same here, was also the case under iOS 11.x
Needed to login about every 24h.

**Comment by lsf3og** [comment]
Have updated needed info. I think wallabag.it uses the most recent version, but didn’t find the info.

**Comment by bourvill** [comment]
i use version 2.2 server instance. Just upgraded to 2.3.3. I will do some tests, stay tuned

**Comment by bourvill** [comment]
Thanks for your screenshot @JanJastrow I really appreciate it

I am working on a version 3.0 of the application. I work on these errors, I hope to finish a reliable application that will meet your expectations. Thank you for your patience and understanding

**Comment by lsf3og** [comment]
Hi,
cool. Thanks for a great app.
Am 13. Sep. 2018, 09:29 +0200 schrieb Maxime Marinel <notifications@github.com>:

**Comment by bourvill** [comment]
if you are crazy and would like test a next release a beta is available : https://testflight.apple.com/join/RF9hzKHt

**Comment by lsf3og** [comment]
Just entered the beta. Will get back to you after some days.
Am 8. Nov. 2018, 14:48 +0100 schrieb Maxime Marinel <notifications@github.com>:

**Comment by lsf3og** [comment]
Hi Maxime,
App seems to be working fine, but I think I will wait for a few days more?
Am 8. Nov. 2018, 14:48 +0100 schrieb Maxime Marinel <notifications@github.com>:

**Comment by bourvill** [comment]
Hello,
Yes, you can wait and use this beta until the end. I will send more beta before the release. All comments are welcomed

**Comment by bourvill** [comment]
3.0.0 is released thanks
