### ISSUE TITLE
Why is Google Analytics integrated?

### ISSUE THREAD

**Issue by froschdesign** [wallabag/ios-app#150]
| Q             | A
| ------------- | ---
| Device?       | iPhone and iPad
| Device Os version    | 11.4.1
| App Version   | 2.3.3
| Wallabag server version | 2.3.2

### Question

Can anyone explain why Google Analytics is integrated with this app?

https://github.com/wallabag/ios-app/search?q=google+OR+analytics+OR+gai

**Comment by bourvill** [comment]
if you know how to search for google analytics in a project you may be able to look for why

**Comment by froschdesign** [comment]
Sorry, you misunderstood me!

There is no privacy police in the Apple App Store, not in the app and not here on GitHub.
And a user can not confirm, disclaim or deactivate the tracking.
(Keyword: GDPR)

**Comment by bourvill** [comment]
RGPD like a boss... look your website... https://froschdesignstudio.de I cannot choose tracking policy ....

On upcoming release you can disable tracking in wallabag-ios app...

**Comment by froschdesign** [comment]
There is a difference, if you move within the legal framework or completely hide something. But my website is not the topic!

---

Some background to my initial question:

Many Wallabag users choose this kind of software and service for privacy reasons. But this app breaks with this.
If you asked for _voluntary_ help within the app, then I would agree. But at the moment we have no difference to services and apps like [Pocket](https://getpocket.com/privacy).

**Comment by bourvill** [comment]
> On upcoming release you can disable tracking in wallabag-ios app...

**Comment by froschdesign** [comment]
@bourvill 
Sorry, I saw that but forgot a comment: Great and thank you in advance! 👍
