### ISSUE TITLE
Disable the preview picture

### ISSUE THREAD

**Issue by ghost** [wallabag/ios-app#151]
### Improvement
Please add an option to disable the preview picture in order to a have a minimalist list of articles.

Thanks!

**Comment by thibaultamartin** [comment]
The Wallabag app is being rewritten. Current major won't get a fix for this, and it's not yet planned for the 5.0.x versions. We're focusing on polishing the existing features before diving into new ones.

If you want to join the beta, you can [follow the Testflight link](https://testflight.apple.com/join/RF9hzKHt). Keep in mind the beta still is unstable, and any update can completely break the app (and potentially do some nasty things on your Wallabag instance).

I'm not sure I got when you want right: do you want an option to disable displaying the preview image in the article itself, or in the article list so you can get a more compact article list?
