### ISSUE TITLE
Cannot Finalize the authentication

### ISSUE THREAD

**Issue by StephaneColson** [wallabag/ios-app#152]
| Q             | A
| ------------- | ---
| Device?       | iPhone
| Device Os version    | 11.4.1
| App Version   | 2.0
| Wallabag server version | 2.0

### Steps to reproduce/test case

I'm using https://app.wallabag.it created a new API client, add this in the iOS app, but at the end of the authentication process, when I click on "Suivant" this button is now greyed and it's blocked on this step. I cannot finalize the configuration, there is no error message.

Any idea ?

![img_0017](https://user-images.githubusercontent.com/1481595/44975823-be0dd200-af63-11e8-9083-be27b65a1e8f.jpg)

**Comment by StephaneColson** [comment]
I’m not alone

![Image](https://i.imgur.com/sDtYcRc.jpg)

**Comment by StephaneColson** [comment]
Thanks, now it’s ok, I probably mistyped something when I tried before.

--
Stéphane Colson

**Comment by bourvill** [comment]
Great! I am rewriting the application completely (version 3.0) I included this fix for version 3.0.
