### ISSUE TITLE
Wallagag iOS app crashes when opening some articles 

### ISSUE THREAD

**Issue by StephaneColson** [wallabag/ios-app#154]
| Q             | A
| ------------- | ---
| Device?       | iPhone
| Device Os version    | 12.0
| App Version   | 2.3.4
| Wallabag server version | 2.0

### Steps to reproduce/test case

Have some linkedin links saved (for example https://www.linkedin.com/jobs/view/875940560/)
Try to open it in the iOS app => crash

### Logs

[wallabag-2018-09-30-210817.ips.zip](https://github.com/wallabag/ios-app/files/2431914/wallabag-2018-09-30-210817.ips.zip)

### Additional information
Same article can be opened in a desktop browser

**Comment by luckydonald-trash** [comment]
Seems it is definitely happening on empty (textless) articles.

**Comment by luckydonald** [comment]
Seems it is definitely happening on empty (textless) articles.

**Comment by bourvill** [comment]
if you are crazy and would like test a next release a beta is available : https://testflight.apple.com/join/RF9hzKHt

**Comment by StephaneColson** [comment]
Not afraid! Let’s test 😉

--
Stéphane Colson

**Comment by StephaneColson** [comment]
Everything is fine, at least with “empty” articles. Thanks 👍

--
Stéphane Colson

**Comment by bourvill** [comment]
3.0.0 is released thanks
