### ISSUE TITLE
Crash loop after refreshing

### ISSUE THREAD

**Issue by Supermassivesheep** [wallabag/ios-app#155]
| Q             | A
| ------------- | ---
| Device?       | iPhone SE
| Device Os version    | 12.0.0
| App Version   | 2.3.4
| Wallabag server version | 2.3.3

### Steps to reproduce/test case

I don't know the cause or if there's a conflicting article.

1. Freshly install the app
2. Fill in credentials like normal
3. Refresh your links
4. Crash loop

From the access log of Nginx:

```
10.0.0.10 - - [26/Oct/2018:15:20:43 +0200] "POST /oauth/v2/token HTTP/1.1" 200 275 "-" "wallabag/2.3.4 (fr.district-web.wallabag; build:115; iOS 12.0.1) Alamofire/4.7.2"
10.0.0.10 - - [26/Oct/2018:15:20:43 +0200] "GET /api/entries?page=1 HTTP/1.1" 200 137902 "-" "wallabag/115 CFNetwork/974.2.1 Darwin/18.0.0"
```

Wallabag prod.log has nothing.

Is there a way to send you a crash log?

**Comment by Supermassivesheep** [comment]
Installed the beta (I am crazy, makes life fun), the app crashed when I put in my username and password. Also instantly crashed after opening it back up.

**Comment by bourvill** [comment]
Thank for your feedback. I just receive some crashlog. I will try to fix the problem shortly

**Comment by bourvill** [comment]
3.0.0 is released thanks
