### ISSUE TITLE
Wrong "reading time" if > 1 hour

### ISSUE THREAD

**Issue by notFloran** [wallabag/ios-app#156]
| Q             | A
| ------------- | ---
| Device?       | iPhone and iPad
| Device Os version    | 12.1
| App Version   | 2.3.4 and 3.0.0 beta
| Wallabag server version | 2.3.3

first of all, thanks for the app !

I found a little bug with the reading time, when it > 1 hour, the app display only the minute(s) after the hour.

iOS app : 1 min

![image](https://user-images.githubusercontent.com/523981/48966309-5a79ca80-efcf-11e8-9a34-b00523bb6472.jpg)

Web : 61 min

<img width="437" alt="capture d ecran 2018-11-24 a 09 52 44" src="https://user-images.githubusercontent.com/523981/48966305-38804800-efcf-11e8-839c-9cecc4b0a2a2.png">

### Steps to reproduce/test case

Add an article with a reading time > 1 hour, example: https://medium.com/@ayyyvocado/la-culture-du-crunch-chez-rockstar-games-vue-de-lint%C3%A9rieur-d121e14737be

**Comment by bourvill** [comment]
Fixed, will be in 3.0.2 release. Thanx

**Comment by rapedapeda** [comment]
I don't want to bump a already closed item. But in version 3.0.2 (using server 2.3.6) all my reading times are formatted as follows: "12:06:00 AM" (should be 6 min).
