### ISSUE TITLE
Unable to log into self hosted with an

### ISSUE THREAD

**Issue by TinkerFu** [wallabag/ios-app#159]
| Q             | A
| ------------- | ---
| Device?      Xperia x Compact
| Device Os version    Android 7.11
| App Version   2.02 (106)
| Wallabag server version Cloned from git about a week ago. 

### Steps to reproduce/test case

Clean install of self hosted server.  Works from the web interface but unable to connect via android. 

Getting this in the log. 

xxx.xxx.xxx.xxx - - [10/Dec/2018:21:09:35 +0100] "GET / HTTP/1.1" 302 4089 "-" "okhttp/3.8.1"
xxx.xxx.xxx.xxx - - [10/Dec/2018:21:09:35 +0100] "GET /login HTTP/1.1" 200 1517 "-" "okhttp/3.8.1"
xxx.xxx.xxx.xxx - - [10/Dec/2018:21:09:35 +0100] "GET / HTTP/1.1" 302 4089 "-" "okhttp/3.8.1"
xxx.xxx.xxx.xxx- - [10/Dec/2018:21:09:35 +0100] "GET /login HTTP/1.1" 200 1517 "-" "okhttp/3.8.1"
xxx.xxx.xxx.xxx - - [10/Dec/2018:21:09:36 +0100] "GET /login/ HTTP/1.1" 404 4050 "-" "okhttp/3.8.1"

Running behind apache2 as a named virtual. Document root is ../wallagab/web
Rewrite is on
Site URL is set correctly. 

Site is https:// so my guess is something is not right since its erroring on HTTP.

**Comment by bourvill** [comment]
You use android device ? You are on iOS repository

**Comment by TinkerFu** [comment]
I'm sorry, I didn't even realize.

**Comment by bourvill** [comment]
No problem, I hope they can help you on the android depot.
