### ISSUE TITLE
can't logon with ver 3.0.0

### ISSUE THREAD

**Issue by lilarcor** [wallabag/ios-app#160]
hello,
I was using 2.3.4 on IOS 12.1 , after I upgrade to 3.0.0, it doesn't allow me to logon any more. I am using custom port as 443 and 80 are disabled by local ISP. I am not sure if the v3 client doesn't support custom ports any more.
The error info is said
Whoops looks like something went wrong. Check the url, don't forgot http or https

Please help.
Thanks.

**Comment by bourvill** [comment]
Hello,
sorry for the decay, i try to find the problem and send the change this day.

Apple's verification center will soon be closed for vacation. The app and patch may not be released immediately

**Comment by lilarcor** [comment]
thanks for the update. I will wait for the new release

**Comment by bourvill** [comment]
The version just been accepted by apple. She should quickly on your phones. I close the request, but if you still have a problem open a new

**Comment by lilarcor** [comment]
I just update 3.0.1,still same

**Comment by bourvill** [comment]
Can you send your server url in private ? send me an email to support@district-web.fr

**Comment by neilzone** [comment]
This worked for me, whereas 3.0.0 was not working. Thank you!

**Comment by lilarcor** [comment]
I have sent mail to you. Thanks.

**Comment by bourvill** [comment]
I close this issues follow #162
