### ISSUE TITLE
Source code for version 3.0.0 - 3.0.4 is missing

### ISSUE THREAD

**Issue by froschdesign** [wallabag/ios-app#161]
| Q             | A
| ------------- | ---
| App Version   | 3.0.0, 3.0.1, 3.0.2, 3.0.3, 3.0.4

The source code with commits and release for the versions from 3.0.0 to 3.0.4 are missing here on GitHub (in this repository). There is no hurry, but it would be nice if it were available.

Thanks in advance!

**Comment by froschdesign** [comment]
@j0k3r @bourvill 
What's the problem here? Is the Wallabag iOS app no longer a open source project?

Some information about the status and the development of the iOS app would be good, because at the moment I feel that the app is going in the wrong direction _– in my opinion_. First, an user tracking was built in and now the app seems to be based on closed source.
If so, that's not a problem, but it should be communicated!

Thanks in advance!

**Comment by bourvill** [comment]
in the coming weeks an application will be published as well as the source code, it will also remove the "tracking".
To respect the philosophy and essence of wallabag which are the success of wallabag

**Comment by froschdesign** [comment]
@bourvill 
First, thanks for the quick response!

> To respect the philosophy and essence of wallabag which are the success of wallabag

Great, that's exactly how I understood the whole project.

**Comment by froschdesign** [comment]
Looks good now: "Remove analytics and start cleaning" ( bbb5eee5a7464991b5d2224e51991e6e86589809) 👍
