### ISSUE TITLE
3.0.1 still not accepts custom port in server URL

### ISSUE THREAD

**Issue by lilarcor** [wallabag/ios-app#162]
Same error I experience in 3.0.0

**Comment by bourvill** [comment]
After verification you use server version 2.3.5 which has just been released, it is not yet tested on the application. The error message is not explicit. 

I work on it. Sorry for the inconvenience.

If you can wait and return to version 2.3.4 of the server, it works

**Comment by guillaumebriday** [comment]
Same issue here with 2.3.5

**Comment by bourvill** [comment]
2.3.5 is not yet tested on the application. The error message is not explicit and the app refuse to connect to this server version. i work on it

**Comment by guillaumebriday** [comment]
Awesome ! Thank you @bourvill 👍

**Comment by bourvill** [comment]
3.0.2 is ready with the fix. AppStore finish his holiday today(12/27). Review will be long but is now in progress. Stay tuned

**Comment by guillaumebriday** [comment]
Yeah 🎉 I got the update today and it works perfectly fine with 2.3.5 !

Thank you @bourvill ! 🙌

**Comment by bourvill** [comment]
Happy reading ;)
