### ISSUE TITLE
iOS app

### ISSUE THREAD

**Issue by milkywade** [wallabag/ios-app#166]
Hi - the iOS app does not cache wallabag content and requires a server connection to consult saved articles which is a deal breaker for me as I need to read articles anywhere.

Do you know of an alternative which does cache ?

thanks

**Comment by j0k3r** [comment]
As far as I know the app should cache article.
Which app are you using?

**Comment by milkywade** [comment]
Hi - app name is "wallabag reader" by "maxime marinel", version 3.0.4. Is this the correct one ?

When offline, the app complains
-  when I open it, it shows an error message "Unsupported version; it looks like you're using an unsupported server version. use the application with caution"
- when trying to share an article I'm reading via the ios share feature to the wallabag app, a super-imposed error will say "Error. please open app and try to add manually your url"

In all these use cases, I would expect that the app works and caches the URL until it can connect to the server again.

Thanks!
![app name](https://user-images.githubusercontent.com/43685172/52442157-beb62000-2b22-11e9-91e5-0d6a6cc11604.png)
![issue when launching app and offline](https://user-images.githubusercontent.com/43685172/52442160-bf4eb680-2b22-11e9-8a06-5a4bab45f108.png)
![issue when sharing article to app and offline](https://user-images.githubusercontent.com/43685172/52442161-bf4eb680-2b22-11e9-8fbd-9da1977aa01d.png)

**Comment by milkywade** [comment]
FYI I just downloaded Wallabag Pro. Works like a charm where this one does not.
