### ISSUE TITLE
Some iOS specific issues encountered by a regular user

### ISSUE THREAD

**Issue by vdbm** [wallabag/ios-app#179]
| Q             | A
| ------------- | ---
| Device?       | iPhone and iPad
| Device Os version    | 12.2
| App Version   | 2.0
| Wallabag server version | app.wallabag.it

Overall I am quite happy with Wallabag, but here are some iOS-specific issues that I share with you in the hope that it can be useful in your further development.

I run FieryFeeds to read rss feeds from Inoreader and now also saved Wallabag articles.
From within FieryFeeds I can see (and read) - all, unread or starred - Wallabag articles, and also see my Wallabag tags and select - all, unread or starred - articles that have a particular tag.
Moreover, I can save an interesting article to Wallabag from any app using the iOS share extensions, but to make that work I had to download the Wallabag 2 official app.

- Issue 1: I cannot tag newly saved Wallabag articles using Fiery Feeds or the Wallabag app.
- Issue 2: The Wallabag app is too limited. Fiery Feeds provides exactly the same functionality but has much more visual customization options in terms of fonts and settings, so I prefer to use FieryFeeds for now.
- Issue 3: The only way that I can tag newly added articles on Wallabag is by going to app.wallabag.it within a browser. The mobile site also doesn't allow any customization in fonts or screen color (e.g. dark mode).

Thanks for the great development!

**Comment by bourvill** [comment]
Thank you for taking the time to leave a comment.

When I read your comment, there are two problems.

The tags are missing.
And visual customization.

I think tags are the most important feature requested by users.
And then there will come the visual customizations.

The app is starting to have good stability but there is still something missing for secure developments. I work actively on it

You can expect an upcoming arrival of tags.

**Comment by vdbm** [comment]
The FieryFeeds issue has been fully addressed by the latest FieryFeeds release. With Wallabag now integrated within Fieryfeeds, the app is only useful now because of the iOS Share extension that it provides, which allows me to save articles from any app to Wallabag.
