### ISSUE TITLE
cannot login to v2.wallabag.org

### ISSUE THREAD

**Issue by brabalan** [wallabag/ios-app#2]
I get a login error from the app, but it works from the web. How can I help debug this? (Note that I created a new client id, see #1.)

**Comment by benbeton** [comment]
do you have a self hosted version? Which wallabag version are you using?
Do you use SSL? (https://..)

**Comment by bourvill** [comment]
In server registration step, don't forget http:// or https:// before your url

**Comment by brabalan** [comment]
I'm using v2.wallabag.org. And yes, the issue was the missing https. It would be nice to mention it on the form.

**Comment by bourvill** [comment]
In next release we check if url work 
Registration add check #21

**Comment by magefesa** [comment]
I have ver 2.1.5 on a docker, i can access from Chrome,extension and Web, but not from my ios app... Why please ?? 
Here my setup 

http://my_localIP:8111
ClientID and secret ID provided from developer section
User and password (used on web app and accessing without problems)

What the hell is happening please ??? 
Thanks oin advacne !

**Comment by j0k3r** [comment]
> http://my_localIP:8111
Is your iPhone connected to the same wifi as your server?
The local ip might not work outside of your network. Like in the wild, in the street, etc..

**Comment by magefesa** [comment]
Yes ! Everithing checked ! Logically my local ip is for "local" connections, then i would try using my domain. But is not working even from my "intranet"... Any ideas ? 
Look my seup 👍 

- Token(for IOS client)
http://d.pr/i/avyT
- http://d.pr/i/oPxM

- Here is my Docker 👍 
http://d.pr/i/S2xn

- Here is my access through WebBroser working fine : (on my iphone works also ):
http://d.pr/i/qiIS

So...what is wrong ?

**Comment by magefesa** [comment]
The solution 👍 
 http://local_ip:8111/app.php 

Great !!!!
