### ISSUE TITLE
Article Reader (text to speech using Siri)

### ISSUE THREAD

**Issue by bourvill** [wallabag/ios-app#215]

**Comment by thibaultamartin** [comment]
Podcast reader seems to be broker with build 245: pressing the music note at the bottom of the screen in article view does nothing

**Comment by bourvill** [comment]
restored with 247

**Comment by thibaultamartin** [comment]
It is now possible to launch the text-to-speech bar at the bottom of the screen. It does not seem to actually read anything after I press the play icon.

For the following article, pressing the music note to launch text-to-speech instantaneously crashes the app: https://framablog.org/2020/02/21/semons-pour-de-bon-et-pour-demain/

**Comment by bourvill** [comment]
Removed from 5.0.0 release
