### ISSUE TITLE
Using less Android-y graphical patterns

### ISSUE THREAD

**Issue by thibaultamartin** [wallabag/ios-app#223]
Hi and thank you for providing this iOS app for Wallabag.

When using the app, the interface feels very "Androidy" (with a sliding left panel).
Has a redesign been considered?

I quickly drafted what I think would feel much more native on an iPhone

<img width="385" alt="Capture d’écran 2019-10-18 à 17 45 04" src="https://user-images.githubusercontent.com/1688309/67108540-0c654b00-f1cf-11e9-8050-47d42a0d5bec.png">

**Comment by bourvill** [comment]
Hello,
Thanks for your proposition.
The application is currently being rewritten and will use swiftUI

**Tabbar navigation is not the best solution for me.** 
For example for tag management, annotations where will it be put?

Here is an overview of the listing of entries

![Simulator Screen Shot - iPhone 11 Pro Max - 2019-10-18 at 17 49 48](https://user-images.githubusercontent.com/295272/67109148-323f1f80-f1d0-11e9-818b-bde4de960d4a.png)

**Comment by thibaultamartin** [comment]
Nice redesign! It's pleasant to see some activity on the app!

> Tabbar navigation is not the best solution for me.
> For example for tag management, annotations where will it be put?

I'm not quite sure what you mean by that :)
I thought of the tab bar pattern as useful, as it allows to quickly switch between read, unread and starred articles. The tab bar being near the thumb, it's quick and easy to switch between the views.

When in article reading view, I think selecting the text should lead to a "contextual menu" (not sure how it's actually called, the meny which allows to copy and paste) with an option to annotate selection.

Also, I feel like the refresh arrow and the + button may be a bit close, leading to errors. Maybe a "pull to refresh" gesture on the list would solve it?

**Comment by bourvill** [comment]
He's going to have a lot of UX work to do.

In fact, with the latest update ios13 and catalina, Apple provide the way to make applications running on both environment without changing any code.

For example, the pull to refresh has no API provided natively with the latest version, for the simple reason that this feature does not make sense on Mac.
Cell swipes do not make sense either, before we could use it to delete an entry for example.
Now we use the context menus, a long press on ios and natively a right click on mac.

This involves a lot of change in design and use.

--
For the moment, I will not implement tabbar navigation.

But perhaps we can submit to the community the choice afterwards.
I will try to release the application on ios13 and catalina before

**Comment by thibaultamartin** [comment]
Great! If you need user feedback before shipping a production version, it may be a good idea to ship the app in TestFlight?

**Comment by bourvill** [comment]
Thank you very much.

It is important to have feedback and suggestions.

The beta testflight is expected

I will launch a public registration. My twitter account and probably the wallabag official accounts will relay the information.

Thank you very much for your feedback and your interest in the application
