### ISSUE TITLE
All articles lost when refresh launched when offline (or without network connection)

### ISSUE THREAD

**Issue by doc75** [wallabag/ios-app#226]
| Q             | A
| ------------- | ---
| Device       | iPhone
| Device Os version    | 13.1.3 (but reproduced since a long time and at least with iOS 12 also)
| App Version   | 4.1.3 build 222 (also reproduced on previous version)
| Wallabag server version | 2.3.8 (but was reproducible with previous version also)

### Steps to reproduce/test case

**Pre-requisite**:
* Ensure you have a network connection, articles in your wallabag application and that refresh is working fine

**Scenario**:
* Activate the **plane mode** on your device
* force a refresh in Wallabag app by pulling down the article

**Actual Result**:
* all articles disappear from the application

**Expected Result**:
* All articles shall remain
* Nice to have:a warning shall indicate that server is not reachable

This would allow to have a real offline mode. Currently even without forcing the refresh we can loose all the articles when being offline.

**Comment by thibaultamartin** [comment]
This issue is fixed in beta build 232 (cc @bourvill)

**Comment by bourvill** [comment]
Thank for your work and feedback @thibaultamartin
