### ISSUE TITLE
[Beta Missing Feature] Preferences to display unread count in app badge 

### ISSUE THREAD

**Issue by thibaultamartin** [wallabag/ios-app#228]
| Q             | A
| ------------- | ---
| Device?       | iPhone
| Device Os version    | 13.2.3
| App Version   | 5.0.0 Build 230
| Wallabag server version | 2.3.8

### Steps to reproduce/test case

Install the Wallabag app and add a few articles. A badge on the app icon displays the number of articles existing on the server (both read and unread).

### Improvement

* It seems the app badge should only display the number of unread articles.
* Additionnally, a setting to indicate whether to display a badge or not at all is missing

**Comment by bourvill** [comment]
Badges are moved to General> Wallabag
It may not be the best place, but it remains parametrable

Maybe it will be useful to put the parameters directly in the application. But these settings rarely change and find that general setting is a good place

**Comment by thibaultamartin** [comment]
Ah! I see! From an end user standpoint it may make sense to enhance discoverability of those settings.

Is it possible to redirect the user to the general > settings from within the app? Since I tried the beta I did not discover that those settings existed!

**Comment by bourvill** [comment]
Link to setting added to the leading bar items area in entries view.
it will be available in 5.0.0 (230) TestFlight

**Comment by thibaultamartin** [comment]
Problem solved in 5.0.0 (231) indeed!
