### ISSUE TITLE
[Beta Missing Feature] Cannot set default view

### ISSUE THREAD

**Issue by thibaultamartin** [wallabag/ios-app#230]
| Q             | A
| ------------- | ---
| Device?       | iPhone
| Device Os version    | 13.2.3
| App Version   | 5.0.0 Build 230
| Wallabag server version | 2.3.8

### Steps to reproduce/test case

Add a few articles and change the tab in the app (e.g. change to _Unread articles_). Close completely the app (swipe it up in the app switcher) and re-open the app: it defaults back to the _All articles_ tab

### Improvement

* Either save the tab to the last one displayed, even after the app has been completely killed
* or add a setting to set the default tab

**Comment by bourvill** [comment]
Default view are moved to General > Wallabag

it might be interesting actually to keep in memory the last tab seen

**Comment by thibaultamartin** [comment]
So current situation is:
* When you open the app after killing it, it defaults to the tab set in the general settings
* When you re-open the app after quitting withing killing it, it keeps the last tab seen

This behavior seems quite good to me. I'd add two improvements though:

* Set up a watchdog so after a long time without opening the app it display to the default tab
* Enhance discoverability of the settings in the general menu

**Comment by thibaultamartin** [comment]
Fixed in build 232
