### ISSUE TITLE
Share to Wallabag does not work

### ISSUE THREAD

**Issue by thibaultamartin** [wallabag/ios-app#231]
| Q             | A
| ------------- | ---
| Device?       | iPhone
| Device Os version    | 13.2.3
| App Version   | 5.0.0 Build 230
| Wallabag server version | 2.3.8

### Steps to reproduce/test case

When browsing an article on a browser, using Share > Wallabag displays a grey "popover" with the Wallabag logo. The Wallabag logo quickly disappears but the popover stays.

The article is not added to Wallabag in the end.

### Improvement

Implement "Share to Wallabag" feature :)

**Comment by thibaultamartin** [comment]
Still broken in build 237 (tested with https://mtlynch.io/solo-developer-year-2/ on Safari)

**Comment by thibaultamartin** [comment]
The problem still occurs with build 238. Tested with Safari on iOS 13 and URL https://hacks.mozilla.org/2020/01/how-we-built-picture-in-picture-in-firefox-desktop/

**Comment by bourvill** [comment]
If you add manually ? It work?

**Comment by thibaultamartin** [comment]
Yes it does work :)

**Comment by bourvill** [comment]
Is an error alert displayed?

**Comment by thibaultamartin** [comment]
It seems to be fixed in build 239! I need to make a bit more extensive testing before definitely closing the issue, but first tests look promising :)

I can already think of two niceties to complete the feature:
- handling the fetch asynchronously. As it seems to be today, the content is fetched by the Wallabg instance, and then it returns either ok or ko. It would feel a lot snappier if the actual fetching was done asynchronously, and if the “share to wallabag” only triggered the fetch and returned immediately
- triggering an automatic refresh when the instance has fetched the article (either successfully or not)

**Comment by bourvill** [comment]
It's a good idea.
But I have a doubt about going through the app to synchronize asynchronously via the app.
When the extension starts adding, it is immediately added to the wallabag server, and I think that the wallabag server must be responsible for the condition of the articles and must serve as a reference for all the applications connected. If an error occurs, the item is lost forever.

Can you give me a typical scenario of adding an article as you think?

**Comment by thibaultamartin** [comment]
I didn't express myself very clearly, let's add some sequence diagram to illustrate it.
My understanding of the way the Wallabag extension works is the following

![mermaid-diagram-20200211085234](https://user-images.githubusercontent.com/1688309/74219052-f6aef080-4cab-11ea-83a0-1ff144aa768d.png)

1. The user in his browser reads an article. He taps on Share to, then Wallabag.
2. The screen whitens, while the Wallabag App tries to understand what is shared to it. It finds the URL of the article, and performs a **synchronous** call to the Wallabag instance
3. The Wallabag instance performs a synchronous call to the actual blog post to retrieve the content
4. The Wallabag instance returns either a 2xx or a 4xx to the Wallabag App depending on whether it could fetch the article or not. The Wallabag App returns a status code to the _Share to_ mechanism. The screen "unwhitens"

During all these steps, the screen remains white and blocks the navigation. I think the best way to handle it is to make the call in (2) _asynchronous_. The Wallabag app would ask the Wallabag instance to fetch an article, but would not wait for the result. It would offer a callback to handle the result, and return immediately.

This callback would wait for the instance's actual response, and would trigger a refresh if the instance could fetch the article.

This way, the server remains authoritative regarding the state of the articles, and the app does not block the user at any time :)

**Comment by bourvill** [comment]
Nice concept.

I think we will transform this proposal into a feature.
It will launch the application on the store. because the extension works again

**Comment by thibaultamartin** [comment]
@bourvill I'm leaving the issue open so you can implement the "Share to Wallabag" flow described in my previous message, but I tested the current way of handling things: it works really well!

There synchronisation does not happen automatically after the article has been added on the Wallabag instance (unless the issue comes from the very low signal I get in the train), I added an entry to the list in #232
