### ISSUE TITLE
Card as UI is not practical

### ISSUE THREAD

**Issue by Crocmagnon** [wallabag/ios-app#235]
| Q             | A
| ------------- | ---
| Device?       | iPhone and iPad
| Device Os version    | 13.2
| App Version   | 4.1.3
| Wallabag server version | Hosted version

### Steps to reproduce/test case

Use the app with the normal flow: register then view articles. All articles are viewed in a « card » which makes it kind of strange since this is the main content of the app.
Cards are often used as content that should pop over, like opening an article or opening the settings.

### Improvement
I’d suggest switching the contents: the main content should be « behind » and the first time the app is opened we should see a card prompting for config. We should be able to reopen the card as needed to change the config.

**Comment by Crocmagnon** [comment]
This is obvious when in the settings: they open in the same card as the main content. A natural gesture to close them is to swipe to the bottom. But this closes the main content and moves us back to the authentication screen.

**Comment by bourvill** [comment]
Hello,
iOS 13 introduce some presentation change and wallabag 4.1.3 is buggy with this version of iOS.

Actually no fix as expected soon. I work on rewrite app with the new SwiftUI framework.
You can try the beta : https://testflight.apple.com/join/73Pvd1wL
