### ISSUE TITLE
Status of articles doesn’t sync

### ISSUE THREAD

**Issue by Crocmagnon** [wallabag/ios-app#236]
| Q             | A
| ------------- | ---
| Device?       | iPhone and iPad
| Device Os version    | 13
| App Version   | 4.1.3
| Wallabag server version | Hosted

### Steps to reproduce/test case
Read an article in the app.
Mark it as read.
Pull the articles list to refresh.
The articles are back to their server status. It seems the status is not pushed to the server, but it’s fetched.

**Comment by bourvill** [comment]
will be fixed in the next release wallabag iOS 5.0.0
