### ISSUE TITLE
The app does not handle credentials change

### ISSUE THREAD

**Issue by thibaultamartin** [wallabag/ios-app#237]
| Q             | A
| ------------- | ---
| Device?       | iPhone
| Device Os version    | 13.3
| App Version   | 5.0.0 Build 233
| Wallabag server version | 2.3.8

### Steps to reproduce/test case

1. Create an account on a wallabag instance
2. Install the iOS beta app
3. Create a "client" on the wallabag instance with a client_id and client_secret
4. Set-up the iOS app with the client_id, client_secret, login, and password
5. Do some wallabaging (add/remove/read/star articles)
6. Change user password on the wallabag instance
7. Open the iOS app and launch a synchronisation (rounded arrow at the top right corner)
8. The arrow rotates forever and does not warn that there's a problem with credentials 

### Improvement

The API is secured using an OAuth2 token. This token is retrieved by using the [OAuth2 Client Credentials grant](https://auth0.com/docs/flows/concepts/client-credentials) (_i.e._ sending the client_id, client_secret, username and password as the body of a `POST`request on the `/oauth/v2/token` endpoint of the instance).

When the endpoint is called with invalid credentials, it returns an http 400 code. The payload of the response contains a json object explaining what went wrong.

If the app provided an invalid client_id or client_secret, the instance answers with:
```
HTTP/2 400 
server: nginx/1.17.3
date: Wed, 15 Jan 2020 16:52:49 GMT
content-type: application/json
x-powered-by: PHP/7.2.19
cache-control: no-store, private
pragma: no-cache
strict-transport-security: max-age=31536000

{"error":"invalid_client","error_description":"The client credentials are invalid"}
```

If the app provided an invalid username or password, the instance answers with:
```
HTTP/2 400 
server: nginx/1.17.3
date: Wed, 15 Jan 2020 16:54:25 GMT
content-type: application/json
x-powered-by: PHP/7.2.19
cache-control: no-store, private
pragma: no-cache
strict-transport-security: max-age=31536000

{"error":"invalid_grant","error_description":"Invalid username and password combination"}
```

Taking into account both the http response code and the `error` type returned in the response body should prompt the user for either new OAuth2 client credentials, or for his username and password.

**Comment by bourvill** [comment]
Wow ! Nice bug hunt!
👍🏻
Definitely your work is awesome 👏🏻!

**Comment by thibaultamartin** [comment]
I forgot my password and had to change it on my instance and faced that bug. I though it'd have more chances to be fixed if sent a detailed bug report 😁

**Comment by thibaultamartin** [comment]
Tested on build 242. When the username and password change server-side, the app actually displays a valid message indicated that the credentials are invalid as soon as the synchronisation button is pressed.

The curved arrow keeps spinning though. It may only be an animation issue, but gives user the sensation that the app keeps trying to sync. I think this should be fixed before closing the issue.

**Comment by bourvill** [comment]
In next build I fix the animation loop

**Comment by thibaultamartin** [comment]
If I change the credentials on the server-side, and try to sync on the app, I get a warning message.

If I kill the app and launch it again, I get to the login screen. Is this intended behaviour? Do we want to log the user out if his credentials changed server-side?
