### ISSUE TITLE
Firefox links can not be wallabaged

### ISSUE THREAD

**Issue by eazy2k13** [wallabag/ios-app#241]
| Q             | A
| ------------- | ---
| Device?       | iPhone
| Device Os version    | 13.3
| App Version   | 4.1.3
| Wallabag server version | 2.3.8

### Steps to reproduce/test case

I'm using Firefox in its most recent version 21.0 (16918), but the error has appeared several months ago.

- Open any URL (e.g. https://en.m.wikipedia.org/wiki/Buzz_Aldrin) in Firefox
- Click on the three-dot-menu on the upper right
- Share with
- Select wallabag
- A milky overlay appears for under a second but nothing happens

The site is not beeing added to wallabag.

**Comment by thibaultamartin** [comment]
The _Share to Wallabag_ works in beta (build 242). You can grab the beta with Testflight.

@bourvill I tested with several pages on the beta from Firefox mobile: it introduces an odd bug. While using the extension with Safari works out of the box, when sharing from Firefox two articles are retrieved:
- the actual article
- an empty one but with the same title

**Comment by bourvill** [comment]
fixed in next build 247

**Comment by thibaultamartin** [comment]
Fixed with build 247, thanks a lot!

**Comment by SteadBytes** [comment]
I am experiencing this same issue on the latest version of the app. Sharing from other browsers (Safari, Chrome) works as expected but Firefox does not - the same "milky overlay" described in this issue appears but no entry is added to Wallabag. I'm wondering whether anybody else is able to reproduce this?

**Comment by bourvill** [comment]
Can you share the link ?

**Comment by SteadBytes** [comment]
Seems to happen on any link, but here’s a specific example https://blog.acolyer.org/2017/03/08/redundancy-does-not-imply-fault-tolerance-analysis-of-distributed-storage-reactions-to-single-errors-and-corruptions/
