### ISSUE TITLE
The entries in the article list cannot be swiped

### ISSUE THREAD

**Issue by thibaultamartin** [wallabag/ios-app#243]
| Q             | A
| ------------- | ---
| Device?       | iPhone
| Device Os version    | 13.3
| App Version   | 5.0.0 Build 235
| Wallabag server version | 2.3.8

### Steps to reproduce/test case

1. Create an account on a wallabag instance
2. Install the iOS beta app
3. Create a "client" on the wallabag instance with a client_id and client_secret
4. Set-up the iOS app with the client_id, client_secret, login, and password
5. Do some wallabaging (add/remove/read/star articles)

### Improvement

Make the entries swipable the same way entries in the Mail app are swipable.

![image](https://user-images.githubusercontent.com/1688309/72808641-432d8000-3c5a-11ea-8d02-663b86d10b01.png)

The actions proposed shouldn't be the same depending on the status of the entry.

* **Swipe to the left**: toggle read/unread state
* **Swipe to the right**: toggle starred/unstarred state

The API to use to toggle both read and starred state is [PATCH /api/entries/{entry}](https://app.wallabag.it/api/doc#patch--api-entries-{entry}.{_format}).

**Comment by bourvill** [comment]
With catalyst, I don't plan to activate swipe actions at the moment.
On mac the swipe action does not make sense.
But maybe later on it will be easy to integrate it.
I will leave this item on hold

**Comment by thibaultamartin** [comment]
> With catalyst, I don't plan to activate swipe actions at the moment.

Is catalyst the framework to easily port an iOS app on macOS?
It doesn't sport the swipe action, the same way it doesn't sport _pull to refresh_ anymore?

> On mac the swipe action does not make sense.

The swipe action is actually used on the Mail macOS app :)

<img width="401" alt="Capture d’écran 2020-01-21 à 15 05 23" src="https://user-images.githubusercontent.com/1688309/72811206-758dac00-3c5f-11ea-9efe-6686831ddf19.png">

> But maybe later on it will be easy to integrate it.

Sure, thanks for the feedback!

**Comment by bourvill** [comment]
The catalyst is a process for bringing the application (iPad version) to Mac without a specific code.

Many gestures are no longer provided "natively" by SwiftUI for example only delete swipe are avaible. If you want more swipe you need to code this. Pull to refresh is not provided by list (table list) for example, but by geometryReader and need more code.

I will try to finish sync process before add quality of life update.
But definitely will be nice to have some swipe action and configurable by user

**Comment by bourvill** [comment]
Old but gold.
This feature will be added with simple action, not configurable
