### ISSUE TITLE
Deleting an article does not change view to articles list

### ISSUE THREAD

**Issue by thibaultamartin** [wallabag/ios-app#245]
| Q             | A
| ------------- | ---
| Device?       | iPhone
| Device Os version    | 13.3.1
| App Version   | 5.0.0 Build 240
| Wallabag server version | 2.3.8

### Steps to reproduce/test case

1. Create an account on a wallabag instance
2. Install the iOS beta app
3. Create a "client" on the wallabag instance with a client_id and client_secret
4. Set-up the iOS app with the client_id, client_secret, login, and password
5. Do some wallabaging (add/remove/read/star articles)
6. When reading an article, tap on the trash bin at the bottom right
7. The article is deleted from the wallabag instance and the reading list, but the view remains on the article. There is no user feedback: it feels like the app does nothing

### Improvement

When tapping on the trash bin in _article read_ view, the app should return to the articles list

**Comment by thibaultamartin** [comment]
This is fixed in build 241, thanks a lot!

While this seems to actually delete the entry on the remote server, it may not update the local model fully.

Consider the following scenario:
1. Add an article to Wallabag App
2. Synchronise fully with the server
3. Open article view
4. Tap the trash bin

The view gets back to articles list, where the article does not appear. Then kill the app (swipe up from the multi-task). At launch the app displays the article previously deleted. Triggering a synchronisation with the remote server actually deletes the article from the local list.

**Comment by thibaultamartin** [comment]
This was fixed in build 242

**Comment by thibaultamartin** [comment]
This was broken with build 245. The article is still deleted both from the server and the article list view, but tapping on the trash bin does not switch back to the articles list view

**Comment by bourvill** [comment]
Sorry, 
fixed in next build

**Comment by thibaultamartin** [comment]
No need to apologize, breaking things happens only when you actually do things, so thanks for all your work :)

**Comment by thibaultamartin** [comment]
Fixed in build 246, thanks!
