### ISSUE TITLE
[Beta] UX issue with the side panel

### ISSUE THREAD

**Issue by thibaultamartin** [wallabag/ios-app#246]
| Q             | A
| ------------- | ---
| Device?       | iPhone
| Device Os version    | 13.3.1
| App Version   | 5.0.0 Build 240
| Wallabag server version | 2.3.8

### Steps to reproduce/test case

Install Wallabag 5.0.0 build 240.

The new side panel has one UX limitation: the button to open this side panel is very narrow. This is especially a problem when another app redirects to Wallabag: tapping on this button is often misinterpreted as "get back to previous app"

![Wallabag screenshot](https://user-images.githubusercontent.com/1688309/74632098-e2ad3800-515e-11ea-94b6-8c96e72cfe16.jpg)

It also limits the discoverability of the "Add article" button . This is not much of a problem given the two other ways to add an article:

- Share to Wallabag
- Read clipboard to detect a link and offer to add it to Wallabag

### Improvement

I'm not a UX designer and I don't have many ideas to fix this problem. This area should be avoided since it can conflict with other elements of iOS' UI. Maybe moving the side panel to the right could be a solution?

**Comment by bourvill** [comment]
In the next build, I will add padding to see if it improves the user experience.

I'm not thinking of moving the menu action to the right.


I also plan to keep the add button in the menu for now. Sending to a specific page of the application will allow you to manage many more things directly from this one. Maybe keeping the button as before would still be a good idea.

**Comment by thibaultamartin** [comment]
The padding really does the trick (build 241) ! 

I don’t have a strong opinion on regarding the “+” button.

Leaving it as it was before does not clutter the interface, but given the workflows available to add an article, it should rarely be used anyway :)

**Comment by bourvill** [comment]
I consider it OK in this case.
We will reopen the more specific issue if necessary
