### ISSUE TITLE
UI scrolls down to seemingly random values when switching to article view

### ISSUE THREAD

**Issue by thibaultamartin** [wallabag/ios-app#249]
| Q             | A
| ------------- | ---
| Device?       | iPhone
| Device Os version    | 13.3.1
| App Version   | 5.0.0 Build 245
| Wallabag server version | 2.3.8

### Steps to reproduce/test case

1. Add an article with a picture at the top to Wallabag
2. Synchronise the app
3. Tap on the article to switch to article view
4. The app displays the article but scrolls down a bit automatically

### Improvement

The app should not scroll down at all when switching to article view, except when reading progress has been saved.

**Comment by bourvill** [comment]
I can't reproduce the problem.

Maybe it's related to the article, can you give an example?

**Comment by thibaultamartin** [comment]
I tried to reproduce: it happens when you scroll a bit through the article, and get back to the top, then leave the article view. When getting back to the article view, it scrolls down a bit.

It also seems the progress isn't reliably saved/restored. When scrolling to a position in the article, getting back to the articles list view, and back again to the article view does not restore the position where it was left.

**Comment by bourvill** [comment]
Fixed in 5.0.2
