### ISSUE TITLE
Add a kind of "about" menu

### ISSUE THREAD

**Issue by j0k3r** [wallabag/ios-app#25]
It always interesting to be able to see the version of the app, the author, a link to the website, etc..
Maybe you should add a menu about that

**Comment by bourvill** [comment]
Have you text in mind about the "about" section ?
Simple text with version? Different section about link, version for example ?

**Comment by j0k3r** [comment]
Hmm you can stay simple. For example:

**wallabag v2 for iOS**
version 1.0.0 build 14
Made by Maxime Marinel (@bourvill)
Report issue: https://github.com/wallabag/ios-app/issues
