### ISSUE TITLE
Swiping from article view, back to articles list

### ISSUE THREAD

**Issue by thibaultamartin** [wallabag/ios-app#250]
| Q             | A
| ------------- | ---
| Device?       | iPhone
| Device Os version    | 13.3.1
| App Version   | 5.0.0 Build 247
| Wallabag server version | 2.3.8

### Steps to reproduce/test case

When switching from article view to articles list view, you need to press the "Back" label at the top left corner. Apps such as _Settings_ or _Toot!_ allow you to do a swipe to the right to get back to preview view.

### Improvement

This would be nice to have to polish the UX :)

**Comment by bourvill** [comment]
NavigationView in swiftui provides native behavior but is currently buggy. The workaround with the router therefore prevents this from working.
We will either stabilize on the apple side, or we will put another workaround
