### ISSUE TITLE
Synchronization failing unpredictably for large article count

### ISSUE THREAD

**Issue by codetrick** [wallabag/ios-app#253]
| Q             | A
| ------------- | ---
| Device?       | iPhone & iPad
| Device Os version    | 13.3.1
| App Version   | 5.0.0 build 249
| Wallabag server version | commit b76bf31b

### Steps to reproduce/test case

For my self-hosted wallabag instance with ~900 articles, synchronization would unpredictably halt. Monitoring access log of the httpd daemon shows that the app is retrieving 30 entries at a time, 

```
<ip> - - [07/Mar/2020:14:04:06 -0800] "GET /wallabag/api/tags HTTP/1.1" 200 710
<ip> - - [07/Mar/2020:14:04:06 -0800] "GET /wallabag/api/entries.json?page=1&perPage=30 HTTP/1.1" 200 1195928
<ip> - - [07/Mar/2020:14:04:07 -0800] "GET /wallabag/api/entries.json?page=2&perPage=30 HTTP/1.1" 200 1373885
<ip> - - [07/Mar/2020:14:04:09 -0800] "GET /wallabag/api/entries.json?page=3&perPage=30 HTTP/1.1" 200 1155524
<ip> - - [07/Mar/2020:14:04:10 -0800] "GET /wallabag/api/entries.json?page=4&perPage=30 HTTP/1.1" 200 1073684
<ip> - - [07/Mar/2020:14:04:11 -0800] "GET /wallabag/api/entries.json?page=5&perPage=30 HTTP/1.1" 200 863392
```

Then before the sync would finish, the client stops sending GET requests. The exact page number in which this happens seems random. Sometimes it would stop right at the beginning, sometimes it stops after 10+ pages, and sometimes (although kind of rare) it would finish normally. The app does not display the articles after a partial retrieval.

When synchronization failed, the app has to be restarted for another try.

Before upgrading to this app version, sometimes the synchronization would fail as well. However that usually happens when the app has synchronized with the server at some point in the past, and another synchronization presumably failed and set the article list to blank. After killing and rerunning the app, the first sync always worked. This is not true for the issue I'm experiencing on the current version v5.0.0 build 249.

**Comment by thibaultamartin** [comment]
Related issue: #185

**Comment by bourvill** [comment]
Old issue, don't hesitate to open if the problem still exists
