### ISSUE TITLE
Marking article as read does not sync across devices

### ISSUE THREAD

**Issue by mattallford** [wallabag/ios-app#254]
| Q             | A
| ------------- | ---
| Device?       | iPhone & iPad
| Device Os version    | 13.3.1
| App Version   | 5.0.0 build 249
| Wallabag server version | 2.3.8

### Steps to reproduce/test case

I have around 40 items in my Wallabag instance at the moment. I read and marked 3 items as read on my iPad, but this is not reflected in the web browser or on my iPhone. It doesn't appear that an item marked as read is syncing across devices correctly.

Steps to reproduce:

1. On an iPad, open the wallabag app and open an article
2. Tap on the book icon to mark the article as read
3. Go back to the app main page and go to the "read" tab, confirm the article is listed here
4. Press the refresh icon (assuming this is refresh / sync?)
5. Open wallabag via the web browser or on another device
6. The article does not show as read

On a side note, it may not be related but I wanted to mention it, on the iPad I starred a separate article and then synced, but suddenly 2 of the above 3 items that I had marked as read were now marked as unread on the iPad.

### Improvement
Marking an article as read on any device should sync that flag across all devices.

**Comment by bourvill** [comment]
Bug found! 
Sorry for the inconvenience.
Will be fixed in 5.0.1


_ Step .4 is not required - the desired behavior is to push on the server as soon as the action is performed _
