### ISSUE TITLE
Original Article / Re-fetch Content Functionality

### ISSUE THREAD

**Issue by mattallford** [wallabag/ios-app#256]
When using wallabag via a web browser, when an article is opened, there is functionality to be able to re-fresh the content from the source, and also a button that links to the original article.

There are circumstances where it would be nice to be able to launch the original article when reading the copy of the article within the wallabag iOS app.

**Comment by bourvill** [comment]
Hi, this feature will be in 6.0.0 and in TestFlight soon (build greater than 288)
