### ISSUE TITLE
"Unknown error" on Login

### ISSUE THREAD

**Issue by Giampieroo** [wallabag/ios-app#257]
iPhone 13..3.1
App Version 5.0.0
Wallabag hosted server version 2.0 on app.wallabag.it

Just installed the app for the first time. On login I get "Unknown error". 
Is it possible an 128 characters password doesn't fit the password field?

**Comment by bourvill** [comment]
Hi,
This error is the last (worst) error.

Did you have the application before the last update?
Can you verify the url, your secret / id clients?

**Comment by Giampieroo** [comment]
Hi!
No, this application is new to me. The url, id and secret step works. 
On the last step login/password I get the error.

**Comment by bourvill** [comment]
All parameters can be checked only at the last connection step.
Can you verify your customer ID / secret,
A frequent error: often a space is inserted during copy and paste

**Comment by Giampieroo** [comment]
There is no space at the end. I also verified the id/secret by select all >copy and paste in notes. There is no space at the beginning or end.

**Comment by Giampieroo** [comment]
I removed and reinstalled the app but it gives me the same error.

**Comment by Giampieroo** [comment]
I’m in! I think I know what causes the error. The keyboard blocks the login button, so Yesterday I pressed return to get it out of the way. 
This time, after filling out the password, I pressed back, then next again, and then the login button.

**Comment by bourvill** [comment]
welcome on board!

The application still needs a lot of work, but it is going in the right direction.

The recording step needs a lot of work, but there is also a need to change things on the server side, it will be a long way

**Comment by Giampieroo** [comment]
Thanks :) Keep up the good work!

**Comment by Kemwer** [comment]
Please I’m having the same problem on version 5.0.0  I already checked the client ID and secret and tried with just clicking the login button but I still get the “Unknown error” I also uninstalled the app and client from wallabag.it is there anything else I should try?

**Comment by bourvill** [comment]
Hi @Kemwer can you provide more information about your instance? Private self hosted? Version?

**Comment by Kemwer** [comment]
Thank you for the reply I could work it out :)

**Comment by bourvill** [comment]
Register workflow is more secure in 5.0.1 coming soon.

**Comment by andrewchenshx** [comment]
iOS 13.3.1
Wallabag app5.0.0
self-hosted, https://myip:port
same “unknow error ” when “Login” pressed

**Comment by bourvill** [comment]
Can you test with the latest beta? https://apple.co/2HRfIcY

**Comment by andrewchenshx** [comment]
If the “server” contains port number, the “next” button is disabled (gray)

**Comment by bourvill** [comment]
@andrewchenshx can you create new account on your instance and share your instance with me? 
If you agree send to maxime.m62@gmail.com I will try directly on your instance.
5.0.1 is on edge release and I want to fix your problem before send it to the store

**Comment by andrewchenshx** [comment]
@bourvill sent

**Comment by bourvill** [comment]
Thank @andrewchenshx 
I use your instance for debug. I found two issues.
One it's fixed -> port in address url (available on next beta build)

Second, your ssl is invalid and app cannot use address with invalid ssl certificat. I cannot fix this issue. You can create certificat with letsencrypt or use http only

**Comment by andrewchenshx** [comment]
1) yes, that’s a self-signed certificate. I don’t have a domain name, so I cannot apply for a ssl certificate from     Let‘s encrypt (ip address is not suitable for applying the certificate ). 
2) if I figure out how to tunnel http connection, I will switch to http.

**Comment by bourvill** [comment]
With the 5.0.2 in review by apple registration process is rewritten and error can be more explicit 
(self-signed certificate cannot be fixed)
