### ISSUE TITLE
Double record when I add an article through share options

### ISSUE THREAD

**Issue by nikiie8** [wallabag/ios-app#259]
| Device     | iPhone
| Device Os version  | 13.1.3
| App Version   | 5.0
| Wallabag server version | 2.3.8

When I add an article to wallabag via share button from tinyReader (2.1.0.7) application, I see this article twice in my wallabag list.

**Comment by bourvill** [comment]
Thank you, we will investigate

**Comment by bourvill** [comment]
Can you share the App Store link of your app?

**Comment by nikiie8** [comment]
Sure. please see below
https://apps.apple.com/us/app/tiny-reader-rss/id689519762

**Comment by bourvill** [comment]
hello @nikiie8 your bug is it still present?

**Comment by nikiie8** [comment]
Hi, Looks like now everything works
