### ISSUE TITLE
Missing animation when opening Add entry, About or Tips

### ISSUE THREAD

**Issue by jrabensc** [wallabag/ios-app#264]
| Q             | A
| ------------- | ---
| Device?       | iPhone 8 Plus
| Device Os version    | 13.4
| App Version   | 5.0.1 build 253
| Wallabag server version | 2.3.8

### Steps to reproduce/test case

When I open Add entry, About or Tips there is no animation (sliding) like when I open the Entries page.

### Improvement
Every point in the Menu should use the same type of animation.

**Comment by bourvill** [comment]
ref #252

**Comment by jrabensc** [comment]
Tested, works as expected now.

**Comment by bourvill** [comment]
Thanks for your testing!
