### ISSUE TITLE
Scroll progress not safed when app is minimized or switched

### ISSUE THREAD

**Issue by jrabensc** [wallabag/ios-app#267]
| Q             | A
| ------------- | ---
| Device?       | iPhone 8 Plus
| Device Os version    | 13.4
| App Version   | 5.0.1 build 253
| Wallabag server version | 2.3.8

### Steps to reproduce/test case

Open article and scroll down. Minimize or switch to another app and back to Wallabag. The scroll position is not restored.

### Improvement

Scroll position should be saved and restored.

**Comment by bourvill** [comment]
definitely the craziest bug I've ever fixed.
The backup was well done but the restoration of the application does not call the same process and does not ask the scrollbar to refresh.

It is corrected and will be available in testflight 5.0.2 (263)

**Comment by jrabensc** [comment]
Its working, thank you for your work!

**Comment by jrabensc** [comment]
I found another bug. When I read an article and I get a message which I answer in the popup, the article is scrolled back up.

**Comment by bourvill** [comment]
@jrabensc can you open a new issue with this particular case ? thank you
