### ISSUE TITLE
Home screen quick action

### ISSUE THREAD

**Issue by bourvill** [wallabag/ios-app#27]
Add link for exemple

**Comment by j0k3r** [comment]
You mean 3D Touch shortcuts?

**Comment by bourvill** [comment]
Yes, what do you think about it?
Other shorcut?

**Comment by j0k3r** [comment]
I don't know.
We should check what other apps use.
_Just a remember I don't have 3D Touch on my device_ :grimacing:

**Comment by roukydesbois** [comment]
Hello, 
Having the possibility to add a URL from the home screen would be nice.

**Comment by Gehirnfussel** [comment]
Example:
- Add Article
- Unread Articles
- All Articles
- Starred articles

(I think 4 are the maximum?)

**Comment by bourvill** [comment]
this change will be available in next release 2.2

will introduce 3 quick action, readed articles, unread articles, starred articles
