### ISSUE TITLE
Logout button

### ISSUE THREAD

**Issue by Tschoepler** [wallabag/ios-app#28]
When I couldn't login on my self hosted instance of Wallabag 2, I tried to login on v2.wallabag.org for debugging. After successfully doing so, I couldn't log out to retry with my self hosted instance. 

Thus I uninstalled the WallabagiOS-app beta and now I can't install it anymore. Though this seems to be an issue with Testflight not your app ; ] Unfortunately I can't get a new invitation through https://docs.google.com/forms/d/e/1FAIpQLSdklmm0Tgdmt3QGppZbKx6Yp-aEbutGk0vX1qUy1GL_WMvtBw/closedform

Any other way you can send me a new invitation?

**Comment by j0k3r** [comment]
This is already planned https://github.com/wallabag/ios-app/issues/17
Also, the app is now live on the app store: https://itunes.apple.com/fr/app/wallabag-2/id1170800946?l=en&mt=8

**Comment by Tschoepler** [comment]
aaaaah XD stupid me. Sorry for the issue and thanks for the help ; ]
