### ISSUE TITLE
Scroll progress is sometimes reset when using quick answer functionality in iOS

### ISSUE THREAD

**Issue by jrabensc** [wallabag/ios-app#283]
| Q             | A
| ------------- | ---
| Device?       | iPhone 8 Plus
| Device Os version    | 13.4
| App Version   | 5.0.2 build 264
| Wallabag server version | 2.3.8

### Steps to reproduce/test case

Read article. Get message in WhatsApp. Pull down to quick answer. Input some text and send it. The article is scrolled up again.

Note: It is not easy to reproduce this, but I observed this bug at least two times. I will continue to test this further on.

### Improvement
The article should not scroll up again.

**Comment by mediaformat** [comment]
Even when reading an article, it sometime resets for me

**Comment by bourvill** [comment]
On reading code a found a potential issue when the application didBecomeActive.

I will push some fix on TestFlight this fix is included in build 310
