### ISSUE TITLE
Need some pointers to contribution resources

### ISSUE THREAD

**Issue by philippmayrth** [wallabag/ios-app#294]
### Improvement
Could you point me to some contribution resources?
Some basic documentation of the layout of source files what views map to what names in code and how I can get help if I’m stuck?
Also how to know that a feature I plan on working is not currently being worked on by someone else.

**Comment by bourvill** [comment]
hello, and welcome to this repo.

Do you already have knowledge in swift and swiftUI?

Application Boot with AppDelegate and SceneDelegate.

After this MainView is the start point.

The main code is in the wallabag/ folder and the application views are in wallabag/component/

for the sharing extension the code is in bagit/

Today, I'm almost the only one working on the repository, so you can take any subject and work on it. You can for example say with an issue or a PR that you want to work on the subject and advance at your own pace.

If you need help, or questions I would be happy to help you.

Do not hesitate to tell me your level on technologies, I could adapt to explain things to you

**Comment by philippmayrth** [comment]
> Do you already have knowledge in swift and swiftUI?

I know Swift but I have done more work in ObjC. Im relatively new to SwiftUI and have only recently started a project using it at work.

> Today, I'm almost the only one working on the repository, so you can take any subject and work on it. You can for example say with an issue or a PR that you want to work on the subject and advance at your own pace.

Perfect.

> Do not hesitate to tell me your level on technologies...

Ive been coding for about a decade now. Self thought — like most I guess. Am working for about 5 years in the field. Have done work in ObjC and had a few apps in the store. Im writing backend code in Python mostly after I found PHP limiting.
At my work Im involed in two large projects both using ReactJS.
I am new to contributing to open source projects.
