### ISSUE TITLE
Feedback Beta

### ISSUE THREAD

**Issue by bourvill** [wallabag/ios-app#297]
- When the app is set in unread mode the list first shows all articles then updates after roughly a second to show only unread articles when going back from the article reader view. 
- Sometimes when going back to the article list after finishing and article and marking it as read when I open a different article it displays content of the previous one instead. I only get the new content once I manually sync again. 
- ~~The Text Zoom is not stored after leaving an article so it had to be configured again for each new article.~~
- Deleting an article does not ask for confirmation nor is there a trash folder making it to easy to accidentally delete an article. 
- Grey Text in white background is far from optimal to read if a user has eye problems. 
- Scroll position jumps a bit up when the app is displaying an article but just came back to foreground because either another app was opened or the iOS configuration overlay (the one with the flashlight WiFi setting and so on). Tested with an iPhone

**Comment by jrabensc** [comment]
Is this issue referring to the iOS 14 beta state?

Just updated to the latest public iOS 14 beta, and Wallabag is crashing instantly.

iOS 14.0 (18A5319i)
iPhone 8 Plus
Wallabag 5.2.0 (276)

**Comment by bourvill** [comment]
Hello is not especially for the iOS 14, this issue is the feedback from the previous iOS beta of wallabag. 

I'm under iOS 14 I have not crash. Can you download the latest wallabag beta, and try ?
