### ISSUE TITLE
Share extension on link hangs current app

### ISSUE THREAD

**Issue by kaitwalla** [wallabag/ios-app#298]
iPhone/iPad (both)
13.4.1
Current stable (unclear which version, I switched to beta to see if it was fixed) and beta
Wallabag 2.3.8

When I try to use the share extension on a link, the overlay pops up but then I have to force-quit the app. The link is never added.

### Steps to reproduce/test case

Be in any app (specifically, I've seen it happen from within Wallabag itself, Safari and Feedly) that has a WebView. Press and hold a link, then hit "Share." Find Wallabag, tap. Wait forever.

**Comment by bourvill** [comment]
Hello, and thank you for your feedback and your script.

I thought I had resolved a lot of cases with the current beta of the iOS app.

Is that a special link? Other than image, pdf ?

**Comment by kaitwalla** [comment]
Nope, just regular HTML links.

**Comment by bourvill** [comment]
I managed to reproduce the problem thanks to your detailed scenario.

Thank you so much! I'm working on it now!

**Comment by bourvill** [comment]
Beta submitted with a fix.
Can you install and try ?

**Comment by kaitwalla** [comment]
Thanks so much! Works great on iPad and iPhone. This is the #1 way I use Wallabag (and Pocket/Instapaper before it), so it is MUCH appreciated.

As a side note/feature request, the animation after it's done might be a touch too long? It feels like the fade could be much quicker to get out of the way.

**Comment by bourvill** [comment]
Good idea.
Will reduce 1s to 500 ms in next beta build.
I will close this issues. Thank for feedback. Appreciated
