### ISSUE TITLE
HTML entities in the title field

### ISSUE THREAD

**Issue by jrabensc** [wallabag/ios-app#300]
| Q             | A
| ------------- | ---
| Device?       | iPhone 8 Plus
| Device Os version    | 13.5.1
| App Version   | 5.1.0 build 272
| Wallabag server version | 2.3.8

![image](https://user-images.githubusercontent.com/6616405/84573498-19a7f900-ada1-11ea-8af5-aabfec55f515.png)

![image](https://user-images.githubusercontent.com/6616405/84573515-3cd2a880-ada1-11ea-8916-7fb0ffcea41b.png)

This is the link to the article: https://www.howtogeek.com/675569/why-linuxs-systemd-is-still-divisive-after-all-these-years/

### Steps to reproduce/test case

Save certain article to wallabag and open the overview or the article view in the app.

### Improvement
The app should not display those characters.

**Comment by bourvill** [comment]
Fixed, I will push 5.1.1 shortly
