### ISSUE TITLE
Is this issue referring to the iOS 14 beta state?

### ISSUE THREAD

**Issue by bourvill** [wallabag/ios-app#308]
Is this issue referring to the iOS 14 beta state?

Just updated to the latest public iOS 14 beta, and Wallabag is crashing instantly.

iOS 14.0 (18A5319i)
iPhone 8 Plus
Wallabag 5.2.0 (276)

_Originally posted by @jrabensc in https://github.com/wallabag/ios-app/issues/297#issuecomment-656899529_

**Comment by bourvill** [comment]
@Jo

**Comment by bourvill** [comment]
@jrabensc
Crash are enabled on your device?
Can you enable it ?
General > confidentiality > Analysis (bottom) > Share with development

**Comment by jrabensc** [comment]
I sent some reports using this function you referred to.

**Comment by L1LNT** [comment]
Some apps are not updated to ios 14.0

**Comment by bourvill** [comment]
@jrabensc No crash report sended by apple at this time :( 
Wallabag work on my ios14 device, I think is related to your content :/  crash are occurs after the last sync entries ?

**Comment by bourvill** [comment]
Can you check this double link ? 
https://help.apple.com/xcode/mac/current/#/deve2819c518

https://help.apple.com/xcode/mac/current/#/dev0f3181c2c

Thank

**Comment by jrabensc** [comment]
I checked the links and edited my settings accordingly. Maybe it's an issue with my device. After all, I'm using a clearly marked beta version.

I did not change the content in my Wallabag instance. The app worked until updating to iOS 14 Beta.

I will keep you updated.

**Comment by jrabensc** [comment]
Reinstalled the app, now it's working without any problems. Sorry, should have tried this before.

**Comment by bourvill** [comment]
Nice feedback.
Probably image download issue. 

Crash report can be send by apple after few day. 

Re load app isn't the normal workflow, we follow this issue with attention.
Thank

**Comment by bourvill** [comment]
Ok crashlog receive. It seem to be a crash with Combine framework after deinit.

Waiting for next beta before fix

**Comment by jrabensc** [comment]
Running the newest beta (14.0 (18A5369b)) the bug seems to be fixed.

**Comment by bourvill** [comment]
Thank you for update.
👍🏻
