### ISSUE TITLE
Export data from iOS app

### ISSUE THREAD

**Issue by opsydev** [wallabag/ios-app#316]
I had an issue with my server and ended up losing all of my wallabag data. I have almost all the articles synced to my iOS device. I can see the list of the articles on the device. Is there anyway I can easily export the URLs from the app to import back into a new installation?

**Comment by bourvill** [comment]
Hello,
at this time export from apps isn't exist.

i don't know how many items you have But you can open article in safari to take url...

**Comment by opsydev** [comment]
That's what I have been doing. I have about 400 bookmarks. I guess this is a good time to clean up!

Thanks for the quick reply!
