### ISSUE TITLE
No images in wikipedia articles

### ISSUE THREAD

**Issue by miwasp** [wallabag/ios-app#323]
| Q             | A
| ------------- | ---
| Device?       | iPhone X
| Device Os version    | 14.3
| App Version   | 5.2.4 build 281
| Wallabag server version | 2.4.1

### Steps to reproduce/test case

All wikipedia articles are displayed without images. It doesn't matter if they are synched from the server (where they include all images) or if they are added in the app on IOS (add entry).
Example URL: https://en.wikipedia.org/wiki/Internet

**Comment by bourvill** [comment]
It's strange, some images are not available in the entry page of the wallabag.
I have the impression that it is a problem with the article

**Comment by miwasp** [comment]
This particular article was only an example. I can add ANY wikipedia article and i never get any images.
Long ago there was a similar problem in wallabag server (https://github.com/wallabag/wallabag/issues/3852).
I don't know what exactly the problem was and when it was fixed but this is working now.

**Comment by bourvill** [comment]
Fixed. It's a little hack. Responsive is the problem. So I removed the property that poses a problem.

The fix will be available in version 6.0.0 and in testflight after build greater than 290
