### ISSUE TITLE
Add confirmation to delete article process

### ISSUE THREAD

**Issue by jrabensc** [wallabag/ios-app#326]
| Q             | A
| ------------- | ---
| Device?       | iPhone 8 Plus
| Device Os version    | 14.4
| App Version   | 6.0.0 build 291
| Wallabag server version | 2.3.8

### Steps to reproduce/test case

Long-press an article and hit delete. The article is deleted without any confirmation. Most users are used to a confirmation dialog before actually deleting something.

![image](https://user-images.githubusercontent.com/6616405/104036744-14dee280-51d4-11eb-8391-dccf088b48f5.png)

### Improvement

Add confirmation dialog to delete process.

**Comment by bourvill** [comment]
hello, you can try this on release 6.0.0 or in TestFlight with build greater than 291
