### ISSUE TITLE
Fix alignment of menu entries

### ISSUE THREAD

**Issue by jrabensc** [wallabag/ios-app#327]
| Q             | A
| ------------- | ---
| Device?       | iPhone 8 Plus
| Device Os version    | 14.4
| App Version   | 6.0.0 build 291
| Wallabag server version | 2.3.8

![image](https://user-images.githubusercontent.com/6616405/104037145-9767a200-51d4-11eb-889f-e655a6f6a901.png)

The alignment in the menu is not correct at the icons and at the labels.

**Comment by bourvill** [comment]
![Capture d’écran 2021-01-08 à 22 46 32](https://user-images.githubusercontent.com/295272/104067383-5cc92e00-5203-11eb-96c7-e6e84ad576be.png)

to get the benefits of automatic label alignment I have to transform the menu like this.
  What do you think about this change?

**Comment by jrabensc** [comment]
Looking good. :+1:
