### ISSUE TITLE
Articles list blinks when going back from article reading view

### ISSUE THREAD

**Issue by Crocmagnon** [wallabag/ios-app#331]
| Q             | A
| ------------- | ---
| Device?       | iPhone and iPad
| Device Os version    | 14.4
| App Version   | 6.0.1 build 301
| Wallabag server version | not relevant

### Steps to reproduce/test case

* Use "unread" mode in settings
* Go to the app, in the "unread" tab
* Open an article
* Tap on the back button at the top left

The list shows all articles for a brief moment and then switches back to the "unread" list.

I expected the list to display the previous state, without blinking.

Here's a screencast of the current behavior (taken on iPad but the same is true on an iPhone):

https://user-images.githubusercontent.com/3630554/108620898-6fa06680-742f-11eb-9d93-50ed4cd37736.MP4

**Comment by bourvill** [comment]
Problem solved.
This hot fix will be in next release 6.0.2
thanks for your work describing the bug
