### ISSUE TITLE
Use reading speed configured on server

### ISSUE THREAD

**Issue by Crocmagnon** [wallabag/ios-app#334]
| Q             | A
| ------------- | ---
| Device?       | iPhone and iPad
| Device Os version    | 14.4
| App Version   | 6.0.3
| Wallabag server version | 2.4.1

### Steps to reproduce/test case
* configure a reading speed on the server, for example 400WPM
* Notice that the reading time of entries is adjusted on the web view
* Notice that the reading time of entries is *not* adjusted on the iOS app

### Improvement
The app should use the reading speed configured on the server to compute the reading time or use the reading time provided by the server if the API provides it.

**Comment by bourvill** [comment]
fixed #380
