### ISSUE TITLE
Unknown Error in iOS app (bug?)

### ISSUE THREAD

**Issue by viewsourc3** [wallabag/ios-app#335]
Hello, 

Here's a bit of background info:
| Q             | A
| ------------- | ---
| Device?       | iPhone
| Device Os version    | 12 Pro, 14.4 (18D52) build
| App Version   | 6.0.3 (latest update on App Store)
| Wallabag server version | using Wallabag.it server

I have a new phone and wanted to configure Wallabag on this new phone (everything works well on the older phone). But I have a "unknown error" when I finish entering all the login details.

I have entered "https://app.wallabag.it" as a server (it is not self hosted), copy/pasted the client ID and Client Secret (made sure there are no hidden spaces at the beginning or end), entered my login and password... But have this "unknown error" when I chose to Login. 

I have reproduced all the steps on the Firefox extension with success. 

I have read issue #257 but I'm not sure it helps. 

Any help is appreciated!

**Comment by bourvill** [comment]
Hi sorry for the inconvenience.
I will try this night a new connection on wallabag.it 
To find any issues.

**Comment by viewsourc3** [comment]
> Hi sorry for the inconvenience.
> I will try this night a new connection on wallabag.it
> To find any issues.

Merci! Si je peux apporter une aide complémentaire, n'hésite pas. 👍

**Comment by bourvill** [comment]
Je viens de faire un test sur l'instance wallabag.it et je n'ai pas eu de soucis pour me connecter.
unknown error arrive vraiment quand je n'arrive pas à decoder la réponse du serveur.

Avez vous activé l'authentification deux facteurs par exemple ?

**Comment by viewsourc3** [comment]
non je n'ai pas l'authentification à double facteur d'activée. :-/ 
Est-ce qu'autre chose pourrait causer ce problème?

**Comment by bourvill** [comment]
D'acc. 
Cet erreur arrive quand on arrive pas à décoder la réponse du serveur. Potentiellement une erreur de frappe dans le nom de domaine par exemple

**Comment by viewsourc3** [comment]
J'ai bien inscrit https://app.wallabag.it en adresse de serveur. Client et ID sont copiés depuis mon interface utilisateur et j'utilise bien mon login (pas l'adresse mail) et le mot de passe tels qu'utilisés pour me connecter sur mon compte (y compris copie/pasté depuis Bitwarden...).

**Comment by bourvill** [comment]
Il serait possible de partager vos informations de connection en privée? Afin que je puisse faire un test dans les mêmes conditions ? 
Dans ce cas écrivez moi sur maxime.m62 @ gmail.com

**Comment by viewsourc3** [comment]
sent. thank you!
