### ISSUE TITLE
Archive button

### ISSUE THREAD

**Issue by TwentyH** [wallabag/ios-app#338]
| Q             | A
| ------------- | ---
| Device?       | iPhone
| Device Os version    | 9.0/10.0
| App Version   | 2.0
| Wallabag server version | 2.0

### Improvement
Can we have a button to directly “archive” and item that would close it, take back to the main screen, and move it to a different folder?

**Comment by bourvill** [comment]
hello,
thank for your feedback, you iPhone is under iOS 10?

**Comment by TwentyH** [comment]
No, iOS 14.4.1.

**Comment by bourvill** [comment]
this is the behavior that was in place. but there seems to be a bug. Thanks
