### ISSUE TITLE
Unknown Error when attempting to access WB via iOS/iPad client app

### ISSUE THREAD

**Issue by nbgibson** [wallabag/ios-app#341]
| Q             | A
| ------------- | ---
| Device?       | iPhone && iPad
| Device Os version    | 14.4.1/14.4.1
| App Version   | Current / Current
| Wallabag server version | 2.4.2

### Steps to reproduce/test case

1.  Create a server instance via docker-compose on LAN
2.  Access the server via a given user 
3.  Create a client via [server]:[port]/developer
4.  Access mobile app on a given ios device on LAN
5.  Enter server details, paste in ID/Secret (checking for spaces and other fun surprises)
6.  Insert user:pass via password manager

### Improvement
A more descriptive error message and/or resolving the root cause of the error.

### Note
The server instance in question is not utilizing https or a reverse proxy, access is direct to the IP:Port being leveraged by docker (not exposing to the internet, don't worry). Install is stock to the docker-compose example provided barring tweaks to:

- SYMFONY__ENV__FROM_EMAIL (wallabag@domain)
- SYMFONY__ENV__DOMAIN_NAME (http://[IP]:82)
- SYMFONY__ENV__SERVER_NAME (Wallalan)
- ports (82:80)
- volumes (WB, not mariadb)

Issue occurs for stock wallabag user as well as custom normal user. Chrome extension access via ID/Secret creation works as expected for all tested users.

**Comment by nbgibson** [comment]
Ok, I sorted out the root cause. Looks like the WB server was down or some element of the stack was not running as I didn't think to include a 'restart: unless-stopped' in each of the elements. I'd advise adding such to the example docker-compose.yaml to save well meaning morons such as myself from themselves.

That said, adding a test case for such in the error catching would be advisable. That or simply dump the raw error message to the client as opposed to "Unknown Error" in the event the end user manages to find a new and inventive way to be an idiot. As end users are wont to do.

**Comment by nbgibson** [comment]
Scratch that, ios client is still prompting "Unknown error" for indeterminate reasons. iPad client was successful, so my guess that it was due to redis or the db or lord knows doesn't track. Though it certainly didn't help.

**Comment by bourvill** [comment]
Thank you very much for looking for the problem on your end.
For my part and on the iOs part, I will try to add a better log to help the user understand the error.

Thank

**Comment by yeyeoke** [comment]
I'm getting the same error. Logged in to wallabag successfully using my iPhone, then iPad wouldnt work. Then I reset my passkey and logged in my iPad, then my iPhone couldnt log in.

**Comment by nbgibson** [comment]
Re-attempted on the iOS client today post update while VPN'd into my home network and everything signed in. Don't know why and I'm not sure I want to log back out and test. We can close if needed as my particular issue appears to be resolved, but feel free to keep it open as a dev point for better error messaging.

**Comment by bourvill** [comment]
I think better error messaging is the most important thing to avoid more errors, typos and other small error.

Thanks for your feedback to make a better app!

**Comment by bourvill** [comment]
closed for #347
