### ISSUE TITLE
White splash screen in dark theme

### ISSUE THREAD

**Issue by rakleed** [wallabag/ios-app#342]
| Q             | A
| ------------- | ---
| Device?       | iPhone XR
| Device Os version    | 14.4.2
| App Version   | 6.0.3
| Wallabag server version | 2.4.2

### Steps to reproduce/test case
1. Make sure dark theme is selected in iOS and app settings
2. Open Wallabag

Helpful link: https://stackoverflow.com/questions/56892053/dark-mode-launch-screen-in-ios-13

Screenshot: 
![644C798D-B322-4375-8703-A9A9256592DA](https://user-images.githubusercontent.com/19418601/114324137-359b3900-9b31-11eb-99d9-c226d1561362.png)

**Comment by bourvill** [comment]
Fixed by @HossamSherraa .
Published with next release 6.0.4
