### ISSUE TITLE
Unable to log in to Wallabag.it

### ISSUE THREAD

**Issue by MitchWagnerSD** [wallabag/ios-app#353]
| Q             | A
| ------------- | ---
| Device?       | iPhone XS
| Device Os version    | 14.06
| App Version   | 6.04
| Wallabag server version | Unknown 

### Steps to reproduce/test case

I am unable to log in to wallabag.it. I created a new application, and am pretty sure I am entering the credentials correctly into the app. It works fine when I enter the same credentials into the Wallabag Pro app. 

When I try to log in to Wallabag 2 I get a red UNKNOWN ERROR message. 

### Improvement

This whole process needs to be easier and better documented.

**Comment by bourvill** [comment]
Hello, sorry for the inconvenience, some issues related are in #349 
I close this one.

Thanks for your submission
