### ISSUE TITLE
WallabagKit.WallabagKitError error 1

### ISSUE THREAD

**Issue by lifepillar** [wallabag/ios-app#354]
I have updated my self-hosted Wallabag instance to v2.4.2, after which I have started to get the error in the subject whenever I try to sync from the iOS app. Before the update I have never had any issue with synchronisation. Any idea what is wrong and how it could be fixed?

**Comment by bourvill** [comment]
Can you check your logs on your server when you try sync action on app ?

**Comment by lifepillar** [comment]
Ah, thanks, I should have thought about it myself!

For the record, `var/logs/prod.log` reported directories inside `var/cache` that were not writable. Fixed by recursively `chown`ing `var/cache` to the `www` user.

No idea why the upgrade would change the cache owner, though.
