### ISSUE TITLE
Badge notification number should be something other than what it is

### ISSUE THREAD

**Issue by bennadell** [wallabag/ios-app#357]
| Q             | A
| ------------- | ---
| Device?       | iPhone
| Device Os version    | 14.1
| App Version   | 2.0
| Wallabag server version | 2.0

The app badge appears to be the number of unread articles, which is not really a practically useful number. I'd rather not be reminded of how much reading I've told myself I would do, and then failed to do, unless I Really wanted to make myself read something in particular.

I don't know what else this feature could be used for, but I don't think this fits within the proper use case.

### Steps to reproduce/test case

Have a wallabag instance, have a functional client set up, and have some unread saved articles.

**Comment by bourvill** [comment]
Hello, thank you for your feedback.

The number can be personalized, you can choose the number of favorite articles, or even deactivate it.

How do you imagine this functionality?
