### ISSUE TITLE
App gone from App Store in Sweden

### ISSUE THREAD

**Issue by celebrion** [wallabag/ios-app#36]
Since around one week back the app is no longer available through the Swedish App Store. Why is this? Is there a new version of the app on it's way with support for Wallabag v2?

**Comment by tcitworld** [comment]
Hi,

It doesn't seem to be available in any country any more : http://support.wallabag.org/discussions/problems/527-wallabag-not-available-in-german-itunes-store and https://github.com/wallabag/ios-app/issues/37.

I'll contact the maintainer to know more about this.

Thomas

**Comment by celebrion** [comment]
It's back! Huzzah!
