### ISSUE TITLE
Add actions when swiping an article on the home page

### ISSUE THREAD

**Issue by roukydesbois** [wallabag/ios-app#36]
Today, there is only the possibility to delete the article. It would be nice to be able to archive/mark as read, and star the swiped article.

**Comment by j0k3r** [comment]
Maybe make them configurable will be nice to:
- configure the swipe on the right
- configure the swipe on the left

With these options:
- delete article
- mark as read / unread
- star

**Comment by bourvill** [comment]
available soon in 1.2
