### ISSUE TITLE
Reading time is not aligned with web interface

### ISSUE THREAD

**Issue by Crocmagnon** [wallabag/ios-app#366]
| Q             | A
| ------------- | ---
| Device?       | iPhone/iPad: both
| Device Os version    | not relevant
| App Version   | 6.0.4 build 304
| Wallabag server version | 2.4.2

### Steps to reproduce/test case

See the following issue on wallabag server: https://github.com/wallabag/wallabag/issues/5404

### Improvement
The reading time displayed in the app should be aligned with that of the web version.
I don't know whether the reading speed is exposed by the API though but if it is then we should compute the correct reading time. The linked issue describes how to compute it.

**Comment by bourvill** [comment]
After some experimentation User config are not exposed in api and I cannot retrieve user information like reading time 

@nicosomb @j0k3r @Kdecherf Can help ? How I can retrieve reading time using api ?

**Comment by bourvill** [comment]
Update ref https://github.com/wallabag/wallabag/pull/5673

**Comment by bourvill** [comment]
<img width="508" alt="Capture d’écran 2022-05-23 à 13 17 50" src="https://user-images.githubusercontent.com/295272/169807866-d7efba47-1870-4c57-b6fe-1bf8aa6841a1.png">

On the road!
