### ISSUE TITLE
Share window shows nothing

### ISSUE THREAD

**Issue by helmut72** [wallabag/ios-app#368]
| Q             | A
| ------------- | ---
| Device?       | iPhone/iPad
| Device Os version    | at least 14.x+
| App Version   | at least 6.x
| Wallabag server version | 2.4.2

### Steps to reproduce/test case

Browse a site, open share dialog, choose Wallabag

### Improvement
There is only this transparent window. Is this really normal? Even no "ok" or "cancel" button?

![3DC5B674-42FC-4C39-87E1-366308C5F1E0](https://user-images.githubusercontent.com/1388751/135671125-6aba6fc5-b86f-4df7-8f6f-14ac95fe69ba.jpeg)

**Comment by bourvill** [comment]
Hello sorry for the inconvenience.

This bug can appear are not configured or error with the web page.

Can you try to add the website directly with the app ?

**Comment by helmut72** [comment]
Website will be added, but this window looks strange IMHO. Is this normal? If yes, my issue can be closed. If not, it's an issue.

**Comment by helmut72** [comment]
You have labeled 'needs more information'. Do you need more informations? I just asked if the output is really normal when I add a website. Adding websites are working, but I'm used to add for example tags or at least cancel it. But it's only this big transparent frame with Wallabag logo ... doesn't look normal for me. That's the reason I've asked.

**Comment by Dekyi** [comment]
I have the same issue. Can I provide any information to help?

**Comment by helmut72** [comment]
**You have labeled 'needs more information'. What informations do you need?**

I just asked if the output is really normal when I add a website. Would be cool if someone can say if it's normal or what should be shown.

Adding websites are working, but I'm used to add for example tags or at least cancel it. Like in Pocket. Or in Wallabag App for Android.

But it's only this big transparent frame with Wallabag logo ... doesn't look normal for me. That's the reason I've asked.

**Comment by Dekyi** [comment]
On ios it is the same for me. I can just add a link and have to change it later to create tags or to remove it if necessary. I would consider this as a bug but at least it is working somehow.

**Comment by bourvill** [comment]
Actually only a "waiting" modal is presented during the push on your wallabag instance.

Tag must be added in app and cannot be added during this step.

This Bug is initially opened for "lock" with waiting modal

**Comment by michaelkrieger** [comment]
So is this open as a feature request to be able to add tags to a new addition (right now it just adds it and you have to add tags in the app)?
