### ISSUE TITLE
Consistency between icons and text

### ISSUE THREAD

**Issue by roukydesbois** [wallabag/ios-app#37]
This is more design than functionalities, but I think the app should have or text or icons for the different actions: delete is an icon on the article view but a text when you swipe on the home screen, you have text (read, star) on the article view and icons (delete and share)...
My view is that it would be nicer with icons (and that would make the localization easier ^^)

**Comment by j0k3r** [comment]
I'm personnaly :+1: for icon instead of text.

**Comment by bourvill** [comment]
available soon in 1.2
