### ISSUE TITLE
When switching apps, wallabag scrolls up to start of section.

### ISSUE THREAD

**Issue by jtagcat** [wallabag/ios-app#370]
| Q             | A
| ------------- | ---
| Device?       | iPhone SE (1)
| Device Os version | 14.8
| App Version   | 6.0.4

Related: #283?

### Steps to reproduce/test case

1. Scrol somewhere in the text
2. Go to home screen
3. Open Wallabag
4. You see it scroll up (towards the beginning). Sometimes it's the last paragraph, other times 3-4 screenfuls of text. Very annoying.

Does not happen when the screen is locked and reopened with Wallabag as the active app.

**Comment by bourvill** [comment]
Hello after some try on ios15 I can't reproduce this bug, can you confirm ?

**Comment by bourvill** [comment]
On reading code a found a potential issue when the application didBecomeActive.

I will push some fix on TestFlight this fix is included in build 310

**Comment by jtagcat** [comment]
> Hello after some try on ios15 I can't reproduce this bug, can you confirm ?

Pretty sure I was on 14 when reporting. Can't reproduce any more.

**Comment by jtagcat** [comment]
I ran across this again today, TestFlight 6.1.0 seems to not have it (in the same spot in the same article).
