### ISSUE TITLE
Articles lists stay empty despite articles visible in web version

### ISSUE THREAD

**Issue by chatelp** [wallabag/ios-app#373]
Device? | iPhone/iPad
Device Os version | 15.4
App Version | 6.1.0 / Build 314
Wallabag server version | 2.4.3 / via latest docker-compose

When clicking on the refresh button in the iOS app, I get the following (non-informative) trace in the server log:

`172.18.0.13 - - [28/Feb/2022:14:13:46 +0000] "POST /oauth/v2/token HTTP/1.1" 200 245 "-" "wallabag/314 CFNetwork/1331.0.7 Darwin/21.4.0"
172.18.0.13 - - [28/Feb/2022:14:13:50 +0000] "GET /api/entries.json?page=1&perPage=50 HTTP/1.1" 200 170872 "-" "wallabag/314 CFNetwork/1331.0.7 Darwin/21.4.0"
172.18.0.13 - - [28/Feb/2022:14:13:50 +0000] "GET /api/tags HTTP/1.1" 401 98 "-" "wallabag/314 CFNetwork/1331.0.7 Darwin/21.4.0"`

So there is indeed connection between the client and server. Also I tried disconnecting the client and reconfiguring everything to no avail.

I hope I'm not the only one :/

Thanks for your help.

**Comment by nomadic-me** [comment]
Device: iPhone
Device OS Version: 15.3.1
App Version: 6.1.0 build 314
Wallabag server version: 2.4.3 (latest from [Github](https://github.com/wallabag/wallabag) forked and cloned today)

I have a similar issue where I can "add" articles from the iOS App (and it shows up in the web version)
So the Client API connectivity is working (between iOS App and the Web version). I do not have any issue or error message on my iOS App.

However, when I refresh - I cannot see any of the articles from the self-hosted web version on my iOS App.
let me know if I can support by giving any additonal information.

**Comment by bourvill** [comment]
sorry for the inconvenience, I will investigate soon, i have not tested the latest version of wallabag instance.

strange behavior I see a 401 status code on /tags

**Comment by bourvill** [comment]
Ok issues found!

@nomadic-me  & @chatelp do you have least of 50 entries in your instance ?

**Comment by nomadic-me** [comment]
Just confirming - I have exactly 4 enties (I just started tinkering with this)

**Comment by chatelp** [comment]
Unfortunately I only have 32 entries 🤔

**Comment by bourvill** [comment]
Thanks
I found the bug 😪
if your instance have less than 50 entries the sync process bug.

Despite the testflight the bug is passed.

I prepare the fix very quickly. Sorry for the real disappointment 😖

**Comment by chatelp** [comment]
> Thanks I found the bug 😪 if your instance have less than 50 entries the sync process bug.
> 
> Despite the testflight the bug is passed.
> 
> I prepare the fix very quickly. Sorry for the real disappointment 😖

Thanks so much. And don’t be sorry! It’s free work!!!

**Comment by bourvill** [comment]
TestFlight is ready: if you want try before release https://testflight.apple.com/join/73Pvd1wL

**Comment by chatelp** [comment]
It works! Thanks for the amazing support @bourvill 🤩

**Comment by nomadic-me** [comment]
This is very impressive - on how quickly you resolved the issued. Thank you @bourvill

**Comment by bourvill** [comment]
Fix released in 6.1.1
