### ISSUE TITLE
Add ability to change background color

### ISSUE THREAD

**Issue by j0k3r** [wallabag/ios-app#38]
Actually the background is plain white. It's killing my eyes by night (even with night shift).
It should be cool to be able to choose between some color, like [#FAFAF6](http://www.color-hex.com/color/fafaf6), or [#F2F1ED](http://www.color-hex.com/color/F2F1ED), or [#F6EFDC](http://www.color-hex.com/color/F6EFDC)

**Comment by bourvill** [comment]
Should be nice in setting

**Comment by bourvill** [comment]
closed for Dark theme #42
