### ISSUE TITLE
iOS app unknown error

### ISSUE THREAD

**Issue by martingz** [wallabag/ios-app#382]
In a self hosted config I can not make the iOS app work. Everything else works, android, windows Firefox plugin, windows opera plugin.

On the Wallabag iOS 6.1.1 app I just get “unknown error”

I’m happy to supply any additional information that would help.

**Comment by bourvill** [comment]
Great news! and I'm happy to help you.

Can you see on your wallabag instance some log of connections?

Do you use custom domain? Local network ? Port ?

**Comment by martingz** [comment]
Great. What is the best location to find good log info? I found one log that did show login info from the browsers but for the iOS app it never showed anything (as I remember).

It is using the default port. I’ll be happy to set up a new client for your testing. What is the best way to exchange that info?

**Comment by bourvill** [comment]
You can send me an email to support@district-web.fr with all the required info
