### ISSUE TITLE
Unable to log in to self-hosted Wallabag on AWS via iOS app

### ISSUE THREAD

**Issue by ckykenken** [wallabag/ios-app#384]
Q | A
-- | --
Device? | iPhone
Device Os version | 15.5
App Version | 6.1.1
Wallabag server version | 2.5.1

### Steps to reproduce/test case
1. Host the server on AWS EC2 with docker
2. after installation, create API client
3. Configure the app using the API credentials

Connection works on Android, not on iOS
Also the issue only occurs on public clouds (e.g. AWS, Azure), connection working on a home NAS

**Comment by bourvill** [comment]
Hello, 
do you have more log?
For example server log with connection from wallabag iOS app ?

**Comment by ckykenken** [comment]
Now I could connect using my iPhone, but I have no idea why.
