### ISSUE TITLE
URL

### ISSUE THREAD

**Issue by tmichellemoore** [wallabag/ios-app#392]
Hello, can you tell me the proper URL to enter in the app? I have the ID and secret, but the indication is that the URL is incorrect. Thanks!

**Comment by bourvill** [comment]
Hello, 

is the domain where you can see your entries.

example for https://wallabag.it is https://**app.**wallabag.it

**Comment by tmichellemoore** [comment]
It's readlater.mydomain.com.

**Comment by bourvill** [comment]
Try to add scheme http or https depending your configuration
