### ISSUE TITLE
My wishlist for the app: annotations, progress indication, show oldest first

### ISSUE THREAD

**Issue by papernoise** [wallabag/ios-app#399]
| Q             | A
| ------------- | ---
| Device?       | iPhone
| Device Os version    | 15.6.1
| App Version   | 6.2.0
| Wallabag server version | 2.6.5

I generally read the articles I save to Wallabag on the phone, often offline. Unfortunatelyt he app feels a bit light on features compared to the web version. These are my top 3 feature requests from my wishlist:

### Feature Requests
1. Sorting option to see oldest articles first. This way I don't have to swipe down to the bottom all the time. Could be a little icon on top next to the reload button.
2. adding annotation support to the app (I would use the web UI, but annotations do not work on the phone, at least not on Safari).
3. Nice to have: Adding a a small progress indicator like on the web version that shows reading progress on the article view.

**Comment by bourvill** [comment]
Hello

1. Sorting is already requested #71 
2. Annotation is a big step, and need lot of work I think, duplicate of #167 
3. Can you create a new issue for this specific topic ?

**Comment by bourvill** [comment]
@papernoise  3. in on the road 

![Simulator Screen Recording - iPhone 14 - 2023-08-31 at 14 04 51](https://github.com/wallabag/ios-app/assets/295272/41137b6f-21ac-4a8f-a8ff-005f1d7d7f86)

**Comment by papernoise** [comment]
> Sorting is already requested https://github.com/wallabag/ios-app/issues/71

Oh man, my brain is a bit mushy these days, I even did that request myself in that issue. 

> @papernoise 3. in on the road

Oh cool! that's amazing!
I think this can be closed then.
