### ISSUE TITLE
Cannot add new articles on iPhone

### ISSUE THREAD

**Issue by eazy2k13** [wallabag/ios-app#402]
| Q             | A
| ------------- | ---
| Device?       | iPhone
| Device Os version    | 17.0.2
| App Version   | 7.0
| Wallabag server version | 2.6.7

### Steps to reproduce/test case

Open a website in Safari. Use the share manu to share the site with wallabag. Safari 'twiches' shortly and nothing happens. The site will not be added to wallabag.

Alternative case:
Open a website in Safari. Copy the URL of the website. Open wallabag. IOS asks if I want to insert the URL. I allow the insert. The wallabag dialog 'add new URL <my copied URL>' appears for not nearly a second and disappears again.

**Comment by bourvill** [comment]
Sorry for the inconvenience, new release it's submitted to apple
