### ISSUE TITLE
Text to speech

### ISSUE THREAD

**Issue by PeterLD** [wallabag/ios-app#403]
Is text to speech still available for the iOS app? I saw [this post](https://wallabag.org/news/wallabag-ios-v6/) for v6 which mentioned it's back, but I can't seem to find it in the current version of the app.

Would be huge for me if it's there, or could be brought back, as it's the main thing keeping me on Pocket.

**Comment by bourvill** [comment]
It looks like there is a display bug. I look quickly

**Comment by bourvill** [comment]
Version 7.0.2 will introduce the fix to restore the text to speech feature. Apologies for the inconvenience. I will let you try it out.

7.0.2 is now under review by apple

**Comment by PeterLD** [comment]
@bourvill amazing,thank you!!

**Comment by mariomaz87** [comment]
It's only in English and I can't select the speed, or am I missing something? Thanks :)
