### ISSUE TITLE
［BUG］Unable to log in using HTTP with IP address and port number.

### ISSUE THREAD

**Issue by liuchao0807** [wallabag/ios-app#412]
As described in the title. The app can no longer log in now. Versions prior to 7.0.2 were able to do so with exactly the same configuration. Currently, attempting to log in results in an unknown error being reported.
![image](https://github.com/wallabag/ios-app/assets/22492920/9b039766-161a-4f83-9066-66d6a849a5b9)

**Comment by bourvill** [comment]
Good morning,
first of all sorry for the inconvenience.

Can you give me a URL pattern that you use?

Also can you give me the version of wallabag that you use on your server?

**Comment by liuchao0807** [comment]
> Good morning,
> 
> first of all sorry for the inconvenience.
> 
> 
> 
> Can you give me a URL pattern that you use?
> 
> 
> 
> Also can you give me the version of wallabag that you use on your server?

Hello, developer.
The URL I am using is：http://8.217.199.xxx:17777
I am using Docker Compose. Below is my docker-compose.yml 
![image](https://github.com/wallabag/ios-app/assets/22492920/67731627-d3af-4bda-bd96-14f273c4f26f)

I have just re-executed `docker-compose pull` to ensure all versions are up to date, and then restarted the server side by using `docker-compose down` and `docker-compose up -d`. However, the issue with the client still persists.

**Comment by liuchao0807** [comment]
By the way, I can log in through the browser.

**Comment by lauevrar77** [comment]
I can confirm that I have the same behavior in my iPhone. 

I would really like to investigate but have no information about the error.

**Comment by bourvill** [comment]
Do you have the same pattern ? Or you have path after the port ?

**Comment by bourvill** [comment]
Bug founded I think!

**Comment by lauevrar77** [comment]
I have no certificate. A port and no path. 
If you found the error when will the update be available ?

**Comment by bourvill** [comment]
I just sent the corrective version to Apple. they need to control the version. this may take several days. the corrective version is 7.2.2

**Comment by lauevrar77** [comment]
A peer review from an Apple Engineer haha ? 
Thank you for the bug fix !

**Comment by bourvill** [comment]
Just validated by apple. try to update your app

**Comment by lauevrar77** [comment]
I just updated but I still have the same error. On 26 Feb 2024, at 08:39, Maxime Marinel ***@***.***> wrote:﻿
Just validated by apple. try to update your app

**Comment by bourvill** [comment]
I just saw my error... The version left without the fix... I'm ashamed

**Comment by bourvill** [comment]
The 7.2.3 is available, can you try with this version ?
