### ISSUE TITLE
Error during pushing to your wallabag server (iPhone App 7.20 build 319)

### ISSUE THREAD

**Issue by nameless66** [wallabag/ios-app#413]
Hey there,
Can't send any page by share to wallabag.it with iPhone. iPad works. 

iOS Version on iPhone: 17.3.1

iOS iPad: 17.3

![image](https://github.com/wallabag/ios-app/assets/4205179/ba6ffee5-510b-48ab-9edf-4c010c3386ae)

**Comment by nameless66** [comment]
Pulling from wallabag.it servers works

**Comment by bourvill** [comment]
Have the same issue yesterday, à quick fix will be send to Apple soon
