### ISSUE TITLE
can you make iOS app available on macOS?

### ISSUE THREAD

**Issue by spitfire** [wallabag/ios-app#416]
Can you make iOS app available on macOS? APple Silicon-based Macs (which have been out for a few years) can run iOS apps, and an iPad version of the app would probably work pretty well, and provide Safari extension (which would be very helpful for saving articles)

**Comment by bourvill** [comment]
App is now available "as it" on Mac app store

**Comment by spitfire** [comment]
Thanks! The share extension works - the sheet shows up just for a second in form of a shadow over Safari window, but it does add article I've shared with it to my reading list.
