### ISSUE TITLE
Dark theme

### ISSUE THREAD

**Issue by romu70** [wallabag/ios-app#42]
Guess everyone can understand this one.

**Comment by j0k3r** [comment]
Might be the same as https://github.com/wallabag/ios-app/issues/38

**Comment by romu70** [comment]
Depends, a dark themen means not only the background color, but the text color as well. We close this one and you complete #38?

**Comment by j0k3r** [comment]
We'll let @bourvill decide on how he plan to implement it.

**Comment by bourvill** [comment]
Theme are good idea.
i'll merge your idea with issue #38 and create some themes with dark declination

Like in v1, we will able to change in article view

**Comment by romu70** [comment]
Great guy! I can't wait to test it.
