### ISSUE TITLE
Errors when listing all the entries

### ISSUE THREAD

**Issue by victor10292** [wallabag/ios-app#429]
| Q             | A
| ------------- | ---
| Device?       | iPhone
| Device Os version    | 14.0
| App Version   | 7.4
| Wallabag server version | 2.6.10

### Steps to reproduce/test case

I have wallabag installed in my iPhone. It will connect to the wallabag server hosted in my own server. When refresh the home page to list all the entry list, although all the entries are listed correctly, I happen to find some error messages in var/log/prod.log file. Here is the screenshot of the error. Could you help me why it happens. It seems that the page number is 2 in the request, but I have only 1 page totally.

![2024-12-11_21-00](https://github.com/user-attachments/assets/40d1cff8-ccc5-4ffa-bfd1-783c50c66437)

### Improvement
If your issue involves a suggestion for improvement or a request to add functionality. You can delete this template and describe your request

**Comment by bourvill** [comment]
The synchronization process tries to look at the next page. If it doesn't find anything, it stops

**Comment by victor10292** [comment]
So, do you mean the error message is normal and intentional? If so, is it possible to fix it by catching the exception and dealing with it to avoid the confusing error messages in the log file?
