### ISSUE TITLE
Stronger contrast between read and unread articles

### ISSUE THREAD

**Issue by romu70** [wallabag/ios-app#43]
To me, the difference between read and unread articles is too subtle. Here is an idea: add a small transparency on the whole article row. This would fade out the image and text a bit and emphasize the difference between the 2 states of an article.

**Comment by bourvill** [comment]
what do you think about a bulleted list like Mail app for exemple ?

**Comment by romu70** [comment]
I don't use the Mail app, so I can't say, and I've just seen I probably uninstalled it. You think about a bullets list with white/blue disks, right?

**Comment by bourvill** [comment]
yup!

**Comment by romu70** [comment]
why not, I would say let's implement the code which seems the most simple for you and see of things are going.

**Comment by bourvill** [comment]
this change will be available in 1.2 soon
