### ISSUE TITLE
Improve the meaning of buttons in the article view

### ISSUE THREAD

**Issue by romu70** [wallabag/ios-app#44]
It's not obvious what "read" means in the article view. Of course, after some time, we know, but at the first times, the purpose of this button is questionable.

Use icons: check mark and star icons can make the meaning more obvious.

Use more accurate texts: "mark as read" and "star this article".

**Comment by j0k3r** [comment]
I think it's the same as https://github.com/wallabag/ios-app/issues/37

**Comment by romu70** [comment]
Yes, definitely duplicates #37.
