### ISSUE TITLE
Remove read articles from the "Unread" view

### ISSUE THREAD

**Issue by romu70** [wallabag/ios-app#45]
Use case:
- user selected the "Unread articles" view
- click on one
- mark it as "read"
-> User is back to the "Unread articles" view, but its just read one is still there.

Suggestion: While back to the "Unread articles" view, update the list with very last changes to remove the just read element.

**Comment by bourvill** [comment]
Thanks for your feedback.
We rework entirely the article list and it's planned for the next release.
This bug are referenced in #31

i close this one

**Comment by romu70** [comment]
No problem, thanks.
