### ISSUE TITLE
Lagging action on swipe

### ISSUE THREAD

**Issue by j0k3r** [wallabag/ios-app#53]
The term "lagging" might be a good choice but on a low connection, marking an item as read from the unread list.

- I open the unread list
- I swipe on an article to mark it as read
- the item is still in the list (while I guess you send the request to the API)
- in the swipe list I can see the "mark as unread"

When marking an item as read from the unread list, the item should disappear as soon as I mark it as read even if the request to the API isn't finished.
And that should be the same behavior if I'm on the read list and I mark an item as unread, or on the star list and I mark an item as unstar, etc.

**Comment by bourvill** [comment]
this fix will be available in next release
