### ISSUE TITLE
Crash test case

### ISSUE THREAD

**Issue by romu70** [wallabag/ios-app#54]
Hello,
I think I've a reproducible test case which crashes the application.

1. Open an unread article
2. Go offline
3. Scroll to the end of the articles
4. Go online
5. Click on "Read"
-> Crash.

When I write "go offline", this is for several hours, typically my phone always goes to plane mode at night and online again in the morning.

**Comment by bourvill** [comment]
thank for your feedback.
The token is not refresh.

**Comment by bourvill** [comment]
i try to fix this, the fix will be available in 1.2
