### ISSUE TITLE
support non-standard port in server url

### ISSUE THREAD

**Issue by timmr** [wallabag/ios-app#59]
Actually (v1.1.1) you can not provide a non-standard port in the server url ( e.g. https://my.server.com:1234).
As I use non-standard ports on self-hosted wallabag instances, could you please support them?

I managed to get it working in the simulator by replacing the regex for validating the server url in ServerViewController.swift to 
`let regEx = "((https|http)://)((\\w|-)+)(([.])((\\w|-)+))+(:\\d{1,5})?(([/])((\\w|-)+))*"`

**Comment by bourvill** [comment]
Thanks for your feedback. i try it

**Comment by magefesa** [comment]
Yes please !! Support for different por !!! Thanks!! AMazing York !!!

**Comment by bourvill** [comment]
the fix will be available in 1.2 soon

**Comment by timmr** [comment]
cool - looking forward to it
