### ISSUE TITLE
Share extension not available in some app

### ISSUE THREAD

**Issue by bourvill** [wallabag/ios-app#63]
Like Tweetbot, Firefox for ex

**Comment by j0k3r** [comment]
Same for Chrome. I was about to ask you about that :)

**Comment by gnppn** [comment]
It doesn't work from Feedly ever. :(

**Comment by roukydesbois** [comment]
Doesn't work from TTRSS 2 either. Do you need a list of the applications to support or do you have a "generic" way to handle sharing from all applications?

**Comment by bourvill** [comment]
Probably the fix cover all app. But when we release this fix you can check them. And give some feedback :)

**Comment by roukydesbois** [comment]
You know we will :)

**Comment by bourvill** [comment]
this change will be available in next release
