### ISSUE TITLE
No feedback when posting an article using the share extension

### ISSUE THREAD

**Issue by brabalan** [wallabag/ios-app#65]
The share extension works great, but there is no feedback after hitting the "post" button. I just see that the web view is unresponsive (I assume this is when the posting happens), then it becomes responsive again. Could you have a small animation or indication that posting is in progress, and that it is done?

**Comment by bourvill** [comment]
Thanks for your feedback.
In 1.2 the focus are only to provide quickly this functionality. On next release we focus on UI and more supported app for the shared function

**Comment by bourvill** [comment]
this change will be available in next release

**Comment by brabalan** [comment]
Thanks!
