### ISSUE TITLE
Missing id attribute crashes app

### ISSUE THREAD

**Issue by LordEidi** [wallabag/ios-app#66]
Just noticed, that when the server does not send an id attribute with the entry record, the iOS App (current version from the AppStore) crashes and closes.

The app is then unusable as long as the server is answering requests but no id attribute is sent.

**Comment by j0k3r** [comment]
Well, that's really strange.
Could you be more specific?
What do you mean by an id? Is it the id of the entry? As it should be an autoincrement field, it's nearly impossible to be empty.
Do you have the json of the article from the api?
Could you give us more information about your wallabag instance? Which SGBD are you using? Which version?
Can you read that article using the web interface? Can you share the url to us (even if we can't access it).

In fact, if the article really doesn't have an id, you should be able to read it too in the web interface. And I guess a lot of things must be broken on the web interface too.

**Comment by LordEidi** [comment]
I am not using Wallabag as a back-end. I am running my own back-end. So this is only about the iOS app and me fuzzing the API.

When the iOS application calls this: http://doc.wallabag.org/en/master/developer/api.html#adding-your-first-entry my back-end served data as in the example above. But it lacked:
```
"id": 1,
```
The client received data, but every entry record lacked its "id" field. Which instantly crashes the iOS App, no error message to the user. 

IMHO the app could refuse to work with records lacking an Id, or it could warn the user and do some magic and create Ids on the fly, but it should never crash.

**Comment by j0k3r** [comment]
> I am not using Wallabag as a back-end. I am running my own back-end.

What do you mean? :thinking:

**Comment by LordEidi** [comment]
Have a look at this: https://github.com/LordEidi/wombag

**Comment by j0k3r** [comment]
Well ok.
Sounds interesting even if there is no code at all.

This app is designed to work with a wallabag API.
A typical response from the API **MUST** include an id for the entry, this is a requirement.

As it is written in your readme _the API is not 100% supported yet_,  I can confirm that. The entry json is missing a critical field value: the unique idenfiant for an entry.
