### ISSUE TITLE
Improve offline mode

### ISSUE THREAD

**Issue by romu70** [wallabag/ios-app#69]
Hello,
This Wallabag iOS app is pretty good when the phone gets offline, but here are some suggestions to make this mode even better:

- The app perfectly works when offline....if it has been started when the device was online. Indeed, the app refuses to properly start and login when the device is offline. But such a connection is not needed because the content has been downloaded and can be read without any network.
- Download the graphics parts when the articles are unread. This will greatly improve the offline experience, and I would find totally logical to remove the graphics once the article is read.

Do you prefer I create 2 issues?

**Comment by j0k3r** [comment]
I think there are already 2 issues for that https://github.com/wallabag/ios-app/issues/5 & https://github.com/wallabag/ios-app/issues/15

**Comment by bourvill** [comment]
Yes, i think is duplicate issues.

@romu70  are you ok with @j0k3r ?

**Comment by romu70** [comment]
Shame on me!!

#5 and #15 are totally related to my second point, but the first point is not about caching. As I wrote the app works offline, it just doesn't start.

**Comment by bourvill** [comment]
application doesn't have any article stored locally.

I think issue caching article must be rename offline mode

**Comment by romu70** [comment]
ok great, no matter the title is, it's good to see this need already tracked.
