### ISSUE TITLE
Write a little documentation for configuration

### ISSUE THREAD

**Issue by nicosomb** [wallabag/ios-app#7]
I think we have all the informations here: http://doc.wallabag.org/en/master/user/android.html

**Comment by nicosomb** [comment]
Oh sorry, I updated the documentation website and I forgot to update this issue. 
@bourvill here is the new URL, in french https://doc.wallabag.org/fr/apps/android.html :trollface:

**Comment by Hatseflats** [comment]
Referring to Android documentation in an iOS-app category is not very helpfull?

**Comment by bourvill** [comment]
@Hatseflats Because the Android documentation should serve as an example for writing that of iOS
