### ISSUE TITLE
Sorting options

### ISSUE THREAD

**Issue by gnppn** [wallabag/ios-app#71]
The web version of wallabag has many sorting options (by language, article length, date, photo, etc), it would be nice to have them on the iOS version as well.

Thanks!

**Comment by bourvill** [comment]
i will planned for a next release.
For the release 2.2 i prefer introduce a first step for tags and major bug fix (app freeze)

**Comment by thibaultamartin** [comment]
The Wallabag app is being rewritten. Current major won't get a fix for this, and it's not yet planned for the 5.0.x versions. We're focusing on polishing the existing features before diving into new ones.

If you want to join the beta, you can [follow the Testflight link](https://testflight.apple.com/join/RF9hzKHt). Keep in mind the beta still is unstable, and any update can completely break the app (and potentially do some nasty things on your Wallabag instance).

I leave this issue open to keep track of it. A nice start would be to discuss how it would integrate in v5.0.x UI

**Comment by Crocmagnon** [comment]
At least using the same default sort order as on the web would be nice. Currently the iOS app puts oldest articles first when the web app puts most recent articles first.

**Comment by bourvill** [comment]
Hello @Crocmagnon do you have access to your db of your wallabag instance ? can you check you created time entries ?

**Comment by Crocmagnon** [comment]
I played with the DB and came to the conclusion that the ios app sorts article by `updated_at` where the web app defaults to `created_at`. In my case everything is mixed up because I imported from Pocket. I guess the `created_at` was set to the original date found in Pocket but the `updated_at` was set at the time I imported all the articles.

Here's the sorting I found the iOS app was using:

```sql
select id, title, created_at, updated_at from wallabag_entry where archived_at is NULL order by updated_at desc, id desc;
```

vs the sorting on the web app:

```sql
select id, title, created_at, updated_at from wallabag_entry where archived_at is NULL order by created_at desc;
```

**Comment by bourvill** [comment]
Thanks for your work!

**Comment by bourvill** [comment]
In the 6.0.2 the default sort is now on created_at (before is sorted on id in the app).

More Sorting options is the other release (sorry)

**Comment by cvaugh** [comment]
The ability to sort ascending/descending would also be nice.
