### ISSUE TITLE
Main list auto-refresh on mark as read

### ISSUE THREAD

**Issue by gnppn** [wallabag/ios-app#72]
When reading an article and marking it as read, the app goes back to the main articles list. When you configured the app to only display unread articles on the main screen, you have to manually refresh it to make the read entries disappear. Could it be possible to have it auto-refresh in this situation?

Thanks!

**Comment by j0k3r** [comment]
Duplicate https://github.com/wallabag/ios-app/issues/31
(not an easy one to find, I agree)
