### ISSUE TITLE
Can't login on Wallabag v2 on ios

### ISSUE THREAD

**Issue by jb911** [wallabag/ios-app#74]
Hello,

I can't login on ios app v2.
I get the error : login error and the token are OK (same on android app).

**Comment by roukydesbois** [comment]
Hello @jb911 

To what wallabag server instance are you trying to connect?

**Comment by jb911** [comment]
On my own server instance.
In logs server, I don't have requests from my iPad connected on the same network (wifi)

**Comment by bourvill** [comment]
Many users have this problem. Usually due to a bad copy / paste of the token. Can you verify at the beginning and end that you have no extra space?

**Comment by jb911** [comment]
There is no space. I copied many times and generate one other. But I have always the same problem.

**Comment by j0k3r** [comment]
Since I asked on Gitter, can you install Charles proxy (or an equivalent) to check what goes out of the app when you try to login?

**Comment by jb911** [comment]
I saw that the application try to connect to mydomain.fr instead of mydomain.fr/bag/

**Comment by j0k3r** [comment]
Could you paste the whole host you defined in the first screen of the application?

**Comment by jb911** [comment]
https://mydomain.fr/bag/

**Comment by jb911** [comment]
I have a directory on my Apache server :   <Directory /var/www/wallabag/web>

**Comment by bourvill** [comment]
please try remove the last /

https://mydomain.fr/bag/ 
to 
https://mydomain.fr/bag

**Comment by jb911** [comment]
same problem : "Login error"

**Comment by jb911** [comment]
I use the same token on my android app and chrome extension with no problem

**Comment by jb911** [comment]
Do you have the same problem ?

**Comment by bourvill** [comment]
some users have experienced the same problem.

Solved generally by bad copy paste.

Can you try with this configuration : https://yourdomain.tld/directory/app.php

**Comment by jb911** [comment]
Same problem :(

**Comment by jb911** [comment]
I have also create a new client ID.

**Comment by jb911** [comment]
nobody :(

**Comment by jb911** [comment]
The problem comes from this error : "tlsv1 alert unknown ca (SSL alert number 48)", with my own self-certificate.

Any idea ?

**Comment by j0k3r** [comment]
Yeah it's mostly because your iPhone don't know you certificat, so it can't validate it.
I don't know how you can fix it apart using a valid root certificat.

**Comment by jb911** [comment]
The self certificate and the ca have been installed on the ipad.

**Comment by bourvill** [comment]
Can you try with https://letsencrypt.org ? You can get a free valid certificat.

In any case, ATS are disabled in built-in app.

**Comment by jb911** [comment]
I only use a certificate for the HTTPS access. I don't use certificate authentication.
I don't have problem with my Android phone and tablet.  Only with iOS app.

**Comment by pixi** [comment]
Same problem here but I can't/won't use a certificate. How can the prob be solved?

**Comment by bourvill** [comment]
Hi guys, i prepared a new release 1.3. it Is actually in internal testing. In this version the error message alert will give more message.

When the release will be available, please give me some feedback

**Comment by jb911** [comment]
Sale problem with the new iOS version :-(

**Comment by bourvill** [comment]
Error in alert?

**Comment by jb911** [comment]
Unexpected error

**Comment by jb911** [comment]
I get this message : "SSL Library Error: error:14094418:SSL routines:SSL3_READ_BYTES:tlsv1 alert unknown ca"

**Comment by bourvill** [comment]
Your ssl ca seems unknown on your device.

Have you provided them?

**Comment by jb911** [comment]
I don't use certificate on my device.
SSL certificate are only use to secure connexion.
I tried to add the CA certificate but I get the same error.

**Comment by bourvill** [comment]
You use a self sign certificate ?

**Comment by jb911** [comment]
yes

**Comment by jb911** [comment]
I tried to import root ca to my ipad but I get the same error : 
SSL library error 1 in handshake 
SSL Library Error: error:14094418:SSL routines:SSL3_READ_BYTES:tlsv1 alert unknown ca (SSL alert number 48)

**Comment by jb911** [comment]
Hello,
Do you news about this problem ?

Thx !

**Comment by bourvill** [comment]
Hello,
Sorry but I have no information about this problem.

It is difficult for me to have the same error because of your particular installation.

Today one thing is about the application is permissive, and allows to support url http / https without problem (ATS disabled)

It seems that it is more at the level of iOS and the management of the CA than the application itself

**Comment by pixi** [comment]
Meanwhile I have a Certificate from letsencrypt, https://letsencrypt.org/, but it still shows the "Unknown Error".
When I log in with exactly the same credentials but using just "http" instead of ”https" it works.

**Comment by j0k3r** [comment]
@jb911 @pixi Is there any chance we can have the url of your instance so we can make some tests on our side to try to fix the problem?

If you don't want to share your url publicly, you can talk to us privately using https://gitter.im/bourvill or https://gitter.im/j0k3r

**Comment by pixi** [comment]
Please check your email from your contact form at http://www.j0k3r.net/

**Comment by j0k3r** [comment]
@pixi got it, thanks!

**Comment by j0k3r** [comment]
So, it was a certificat issue for @pixi (wrong domain name regarding the certificat).

@jb911 we are waiting for your instance url (shared privately if you want) to make further tests.
Thanks

**Comment by j0k3r** [comment]
This issue is fairly old and there hasn't been much activity on it. Closing, but please re-open if it still occurs.
