### ISSUE TITLE
Multi-line titles in articles list

### ISSUE THREAD

**Issue by deanishe** [wallabag/ios-app#75]
In the articles list on my iPhone SE, titles are truncated to just 15 or so characters, which is simply too short. I see a lot of "Name of Website:…" and "Name of Series - Par…" entries with no way to tell which article I'm looking at.

Could you add an option to show the full title, or two lines of it at the very least?

**Comment by bourvill** [comment]
Thank for your feedback.
We can plan adjustment in next release.

best regards

**Comment by bourvill** [comment]
this change will be available in next release
