### ISSUE TITLE
Add links in Article to wallabag

### ISSUE THREAD

**Issue by Findus23** [wallabag/ios-app#78]
It would be nice if one could add long tab a link in an article to add them directly to wallabag.

UPDATE: Seems to be the same feature as https://github.com/wallabag/android-app/issues/43

**Comment by j0k3r** [comment]
I think it's related to https://github.com/wallabag/ios-app/issues/63
iOS use share extension but the app doesn't provide that share extension every where for now.

**Comment by bourvill** [comment]
Thank for your feedback, actually i rework the share extension #63 #65 
I think it's possible to integrate this feature in the upcoming release (1.3)

But if it's cost lot of time, i plan for the next release

**Comment by Findus23** [comment]
Ah, sorry. Didn't know it was the same as sharing from other apps

**Comment by Findus23** [comment]
I have just updated the app to 3.03.2017 and sharing works better than before but this (adding links in article) is still not possible as the app freezes whey I try to. The same happens in safari. 

#### Steps to reproduce:

- long tab a link in Safari or wallabag app
- select share...
- select wallabag 
- white rectangle appears and Safari/wallabag app freezes (has to be closed to be usable again)
