### ISSUE TITLE
can't register new server 

### ISSUE THREAD

**Issue by signuntu** [wallabag/ios-app#81]
I had to install my wallabag server completely new. Previously everything worked fine syncing with the iOS App. Now when I want to register my account, I can't enter any server address without receiving the Error message to check the url.
Tried my server address and tried some hints seen here - not working.
Tried https://app.wallabag.it - same result.
Tried deleting the app and reinstalling it - same result.
Tried on a second device with previous wallabag connection - same result.
Tried on a third device without any previous wallabag connection - worked.

iOS 10.2.1 and Wallabag v1.3 installed

**Comment by bourvill** [comment]
Thank for your feedback.

I check this week

**Comment by bourvill** [comment]
Hi, after few test. We have no problem to connect on new server, with already server configured before disconnecting.

Can you try again ?

**Comment by signuntu** [comment]
Thanks for your help. Sorry, its still the same behavior. In the meantime I checked if there is a problem with my DNS. I find it really strange that the error message pops up so fast and I don't see any connection attempts on my server.

**Comment by bourvill** [comment]
The "unexpected error" is thrown when the server don't respond with a status code 200 and when the response don't contain a valid json and the body of json does not contain a key "error_description" in login processus

Do you receive a connection on your server, can you check your log file ?

**Comment by signuntu** [comment]
I don't see any connection attempts from my phone in the wallabag log or other logs which indicate that the app really checking my server.
I'm not sure if it's the same error msg, but I don't see an unexpected error just a error to check the url.

**Comment by bourvill** [comment]
Error are occurred only url page ?

Give me your url please

**Comment by signuntu** [comment]
https://wb.mnium.de

**Comment by bourvill** [comment]
I try just now, and i dont have problem on server page.

**Comment by signuntu** [comment]
I expected that, because 

> Tried on a third device without any previous wallabag connection - worked.

I guess best option right now is: I wait until you release v1.3.1 and report back to you

**Comment by signuntu** [comment]
I found what's causing my problem. It's because I disabled Safari. When I enable Safari I can register my server and afterwards Safari can be disabled again. Everything works as it should.

Thanks for your help.

**Comment by j0k3r** [comment]
Disabled Safari? Hu.
Anyway, thanks for telling us about that.
