### ISSUE TITLE
Regarding fade animation when saving is complete

### ISSUE THREAD

**Issue by n00b12345** [wallabag/ios-app#83]
When a save is complete, the Wallabag extension fades from the screen. This leads to a confusion because the actual fade is complete a few milliseconds after the logo is gone from the screen. And until the actual fading is complete, the rest of the screen remains unresponsive.

This is a subtle issue but can be annoying.

I think abrupt disappearance may be ugly but more beneficial.

**Comment by JanJastrow** [comment]
Yeah, I have the same issue. It feels like you should be able to tap somewhere else when the fading starts, but since the process is not done, you can't do anything.

Maybe a spinner animation for the process would be better and then a shorter fade-animation, that you can cancel with a tap anywhere.

**Comment by bourvill** [comment]
Ok for shorter animation.

**Comment by bourvill** [comment]
this change will be available in next release

**Comment by j0k3r** [comment]
Also, since the displayed square it white, when saving an article which has a primary color white, it's hard to see the animation.
Maybe a smili animation like a notification from the top (like Instapaper) might be better.

**Comment by bourvill** [comment]
Can you post an example @j0k3r ?

For this minor release, i reduce only the time of animation. But for one next release, it's possible to rewrite the animation

**Comment by j0k3r** [comment]
![image](https://cloud.githubusercontent.com/assets/62333/24951585/353940ec-1f75-11e7-9319-dc12642a28a3.png)

**Comment by bourvill** [comment]
Maybe i can try to add little shadow on page.

Can you post image of Instapaper ?

**Comment by j0k3r** [comment]
![image](https://cloud.githubusercontent.com/assets/62333/24951770/da0b4a98-1f75-11e7-9d6f-157e93c0c17f.png)

**Comment by bourvill** [comment]
Ok, i think add shadow it's best quick fix.

Pop up on top it's cool, but the action to close the popup it's bad
I think no action is needed for the user after the posting on wallabag is terminated

**Comment by j0k3r** [comment]
The popup is closing it self after few seconds.
The cross just allow the user to close it faster.
