### ISSUE TITLE
Add a way to add a new article to the list while reading another one

### ISSUE THREAD

**Issue by romu70** [wallabag/ios-app#85]
Hello,
Consider the following use case:

- Wallabag iOS is open and an article is being read
- For any reason, you want to add a new article to your wallabag

The only way I know to do this is to go back to the wallabag list and click on the button to add a new article. But this raises some issues: it's a long list to go back to the list, add the new item and then go to your article again ; and you lose the reading cursor position.

Would be great to be able to add a new article while reading another one.

Thanks.

**Comment by bourvill** [comment]
If we add the button in the action bar at the bottom of an article? Does that sound like a good idea?

**Comment by romu70** [comment]
Yes I guess this is the best solution because it doesn't change the current reading and the cursor position.

**Comment by bourvill** [comment]
Finally i add on top bar, be the same of the main interface.

this change will be available in next release 2.1
