### ISSUE TITLE
iOS client doesn't save read position on an article

### ISSUE THREAD

**Issue by pedro7** [wallabag/ios-app#86]
If I open an article on iOS, read it to the middle and afterwards exit the app by swiping up, when I open the article again, the app has forgotten where I was reading and shows the beginning of the article.

**Comment by j0k3r** [comment]
The API still doesn't have the endpoint for reading process.

**Comment by nicosomb** [comment]
See https://github.com/wallabag/wallabag/pull/2644

**Comment by bourvill** [comment]
can be an enhancement with or without api. We can store locally the position.

**Comment by bourvill** [comment]
this change will be available in next release 2.1
