### ISSUE TITLE
Minor cropping issue with the icon image

### ISSUE THREAD

**Issue by n00b12345** [wallabag/ios-app#87]
There's a very minor cropping issue with the image on the wallabag share extension. I hope the image makes it clear. It shouldn't take too long to fix. If possible, please consider fixing it 👍 

![img_0795](https://cloud.githubusercontent.com/assets/17707852/26574921/de7d982e-4540-11e7-9dbc-1d1c8d7125e0.PNG)

**Comment by bourvill** [comment]
this fix will be available in next release 2.3.2.

Thanks
