### ISSUE TITLE
Add german translation

### ISSUE THREAD

**Issue by bourvill** [wallabag/ios-app#90]

**Comment by jlnostr** [comment]
Which file(s) needs to be translated?

**Comment by bourvill** [comment]
Hi @jlnostr, i made a new pull request #91 
German file are located in
https://github.com/wallabag/ios-app/blob/2.1-dev-i18n/wallabag/de.lproj
and
https://github.com/wallabag/ios-app/tree/2.1-dev-i18n/wallabag/Storyboard/de.lproj

Tell me if you need help

**Comment by jlnostr** [comment]
See 9387a061b024fed0311907b237bdf734593a1b0d.

**Comment by bourvill** [comment]
@jlnostr can you work on this file ? it's now for the app store.

https://github.com/wallabag/ios-app/tree/2.1-dev-i18n/fastlane/metadata/de-DE

**Comment by jlnostr** [comment]
Done.
