### ISSUE TITLE
Can't connect my server anymore

### ISSUE THREAD

**Issue by romu70** [wallabag/ios-app#98]
Hello,
As written on Gitter last week, I'm not able to use this app anymore. Yesterday, I've removed it and re-installed it and it refuses to connect my server with something like : "Unexpected error (1)".

**Comment by romu70** [comment]
My server still works, but indeed something changed: I change the Let's Encrypt certificate because it was outdated. May this be related?

**Comment by bourvill** [comment]
do you use ssl?

**Comment by romu70** [comment]
Yes, just read my new comment, messages crossed.

**Comment by bourvill** [comment]
Yes, this is a possible problem with ssl, is your server configured correctly?

**Comment by romu70** [comment]
I guess yes, I get a green flag within Firefox.

**Comment by bourvill** [comment]
Can you give me the url?
Or send me in private to maxime.m62@gmail.com please

**Comment by romu70** [comment]
Just upgraded my server to 2.2.3. I don't get the error 500 anymore. But the app still doesn't connect :-(

**Comment by bourvill** [comment]
Do you have logs on your server? Apache / nginx log for example attempting to connect from the application

**Comment by romu70** [comment]
Hello. My server is running the official Wallabag Docker image, problem is I don't see any log because the nginx access and error logs are just links to stdout and stderr.

My server has just had a bit of problem because of some bad sectors on my disks. I had to delete the whole wallabag image and container, and start again the procedure from scratch. No change, I still get the error from my iPhone.

I've just tried to create a new Wallabag API client. This doesn't change anything.

**Comment by bourvill** [comment]
Send me an email with your instance and create account for testing please to maxime.m62@gmail.com

**Comment by bourvill** [comment]
this problem is still active?

**Comment by romu70** [comment]
I don't know, I don't use iOS anymore. You can close this issue I guess.
