### ISSUE TITLE
Background fetch doesn’t work

### ISSUE THREAD

**Issue by bourvill** [wallabag/ios-app#99]

**Comment by roukydesbois** [comment]
Hahaha I was about to enter an issue about this :)

**Comment by roukydesbois** [comment]
I also have some weird behaviour when I delete/archive/favourite an article: sometimes it works, sometimes it doesn't. And when I quickly do 2 actions on 2 different articles (2 deletes for example), it goes back to the starting point. I don't know if this issue has the same reason as the background fetch though.
It's also noteworthy to say that I am hosting my wallabag behind an ADSL box - so it can be long to answer.

**Comment by bourvill** [comment]
I think is not the same problem. i create a new issue with this one.

**Comment by bourvill** [comment]
background fetch doesn't work.

We report for next release.

**Comment by bourvill** [comment]
this fix will be available in next release 2.2
